/**
 * Generated by orval 🍺
 * Do not edit manually.
 * LupiraTasks BFF
 * OpenAPI spec version: v1
 */

/**
 * A person the caller has seen across their shared lists (for adding members).
 */
export interface DirectoryPerson {
  principalId: string;
  email: string;
  /** @nullable */
  displayName?: string | null;
}
