/**
 * Generated by orval 🍺
 * Do not edit manually.
 * LupiraTasks BFF
 * OpenAPI spec version: v1
 */

/**
 * A member's authority on a list. Ordered: Owner &gt; Editor &gt; Viewer.
 */
export type ListRole = typeof ListRole[keyof typeof ListRole];


export const ListRole = {
  Owner: 'Owner',
  Editor: 'Editor',
  Viewer: 'Viewer',
} as const;
