/**
 * Generated by orval 🍺
 * Do not edit manually.
 * LupiraTasks BFF
 * OpenAPI spec version: v1
 */
import type { ListRole } from './listRole';

/**
 * Change a member's role on a list (Owner only).
 */
export interface UpdateMemberRoleRequest {
  role: ListRole;
}
