/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Lupira Tasks API
 * Task and command processing backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateShareRequest,
  ProblemDetails,
  RedeemShareRequest,
  RedeemShareResponse,
  ShareCollectionResponse,
  ShareResponse
} from '../models';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getRedeemShareUrl = () => {




  return `/shares/redeem`
}

/**
 * Body `{ token }`. Adds the caller to the linked list — `ReadWrite` → Editor, `Read` → Viewer — and returns `{ listId, role }`. Idempotent: an existing member keeps their current role. Used by the web client to cash in a share link after SSO.
 * @summary Redeem a share link as the authenticated caller (join the list).
 */
export const redeemShare = async (redeemShareRequest: RedeemShareRequest, options?: RequestInit): Promise<RedeemShareResponse> => {

  return customFetch<RedeemShareResponse>(getRedeemShareUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(redeemShareRequest)
  }
);}




export const getRedeemShareMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof redeemShare>>, TError,{data: RedeemShareRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof redeemShare>>, TError,{data: RedeemShareRequest}, TContext> => {

const mutationKey = ['redeemShare'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof redeemShare>>, {data: RedeemShareRequest}> = (props) => {
          const {data} = props ?? {};

          return  redeemShare(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RedeemShareMutationResult = NonNullable<Awaited<ReturnType<typeof redeemShare>>>
    export type RedeemShareMutationBody = RedeemShareRequest
    export type RedeemShareMutationError = ProblemDetails

    /**
 * @summary Redeem a share link as the authenticated caller (join the list).
 */
export const useRedeemShare = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof redeemShare>>, TError,{data: RedeemShareRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof redeemShare>>,
        TError,
        {data: RedeemShareRequest},
        TContext
      > => {
      return useMutation(getRedeemShareMutationOptions(options), queryClient);
    }
    export const getCreateShareUrl = (listId: string,) => {




  return `/lists/${listId}/shares`
}

/**
 * Body `{ access: 'Read' | 'ReadWrite', label?, expiresAt? }`. Returns the opaque token + a ready-to-copy URL. The link grants account-less access at `/shared/{token}` until revoked or expired.
 * @summary Mint a public share link for a list (Owner).
 */
export const createShare = async (listId: string,
    createShareRequest: CreateShareRequest, options?: RequestInit): Promise<ShareResponse> => {

  return customFetch<ShareResponse>(getCreateShareUrl(listId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createShareRequest)
  }
);}




export const getCreateShareMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createShare>>, TError,{listId: string;data: CreateShareRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createShare>>, TError,{listId: string;data: CreateShareRequest}, TContext> => {

const mutationKey = ['createShare'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createShare>>, {listId: string;data: CreateShareRequest}> = (props) => {
          const {listId,data} = props ?? {};

          return  createShare(listId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateShareMutationResult = NonNullable<Awaited<ReturnType<typeof createShare>>>
    export type CreateShareMutationBody = CreateShareRequest
    export type CreateShareMutationError = ProblemDetails

    /**
 * @summary Mint a public share link for a list (Owner).
 */
export const useCreateShare = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createShare>>, TError,{listId: string;data: CreateShareRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createShare>>,
        TError,
        {listId: string;data: CreateShareRequest},
        TContext
      > => {
      return useMutation(getCreateShareMutationOptions(options), queryClient);
    }
    export const getListSharesUrl = (listId: string,) => {




  return `/lists/${listId}/shares`
}

/**
 * @summary List a list's active share links (Owner).
 */
export const listShares = async (listId: string, options?: RequestInit): Promise<ShareCollectionResponse> => {

  return customFetch<ShareCollectionResponse>(getListSharesUrl(listId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListSharesQueryKey = (listId: string,) => {
    return [
    `/lists/${listId}/shares`
    ] as const;
    }


export const getListSharesQueryOptions = <TData = Awaited<ReturnType<typeof listShares>>, TError = ProblemDetails>(listId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShares>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSharesQueryKey(listId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listShares>>> = ({ signal }) => listShares(listId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: listId !== null && listId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listShares>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSharesQueryResult = NonNullable<Awaited<ReturnType<typeof listShares>>>
export type ListSharesQueryError = ProblemDetails


export function useListShares<TData = Awaited<ReturnType<typeof listShares>>, TError = ProblemDetails>(
 listId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShares>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listShares>>,
          TError,
          Awaited<ReturnType<typeof listShares>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListShares<TData = Awaited<ReturnType<typeof listShares>>, TError = ProblemDetails>(
 listId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShares>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listShares>>,
          TError,
          Awaited<ReturnType<typeof listShares>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListShares<TData = Awaited<ReturnType<typeof listShares>>, TError = ProblemDetails>(
 listId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShares>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List a list's active share links (Owner).
 */

export function useListShares<TData = Awaited<ReturnType<typeof listShares>>, TError = ProblemDetails>(
 listId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShares>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSharesQueryOptions(listId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getDeleteShareUrl = (listId: string,
    shareId: string,) => {




  return `/lists/${listId}/shares/${shareId}`
}

/**
 * @summary Revoke a share link (Owner). The token is rejected on its next use.
 */
export const deleteShare = async (listId: string,
    shareId: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getDeleteShareUrl(listId,shareId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteShareMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteShare>>, TError,{listId: string;shareId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteShare>>, TError,{listId: string;shareId: string}, TContext> => {

const mutationKey = ['deleteShare'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteShare>>, {listId: string;shareId: string}> = (props) => {
          const {listId,shareId} = props ?? {};

          return  deleteShare(listId,shareId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteShareMutationResult = NonNullable<Awaited<ReturnType<typeof deleteShare>>>

    export type DeleteShareMutationError = ProblemDetails

    /**
 * @summary Revoke a share link (Owner). The token is rejected on its next use.
 */
export const useDeleteShare = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteShare>>, TError,{listId: string;shareId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteShare>>,
        TError,
        {listId: string;shareId: string},
        TContext
      > => {
      return useMutation(getDeleteShareMutationOptions(options), queryClient);
    }
