/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Lupira Tasks API
 * Task and command processing backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateShareRequest,
  ProblemDetails,
  RedeemShareRequest,
  RedeemShareResponse,
  ShareCollectionResponse,
  ShareResponse
} from '../models';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getPostSharesRedeemUrl = () => {




  return `/shares/redeem`
}

/**
 * Body `{ token }`. Adds the caller to the linked list — `ReadWrite` → Editor, `Read` → Viewer — and returns `{ listId, role }`. Idempotent: an existing member keeps their current role. Used by the web client to cash in a share link after SSO.
 * @summary Redeem a share link as the authenticated caller (join the list).
 */
export const postSharesRedeem = async (redeemShareRequest: RedeemShareRequest, options?: RequestInit): Promise<RedeemShareResponse> => {

  return customFetch<RedeemShareResponse>(getPostSharesRedeemUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(redeemShareRequest)
  }
);}




export const getPostSharesRedeemMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postSharesRedeem>>, TError,{data: RedeemShareRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postSharesRedeem>>, TError,{data: RedeemShareRequest}, TContext> => {

const mutationKey = ['postSharesRedeem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postSharesRedeem>>, {data: RedeemShareRequest}> = (props) => {
          const {data} = props ?? {};

          return  postSharesRedeem(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostSharesRedeemMutationResult = NonNullable<Awaited<ReturnType<typeof postSharesRedeem>>>
    export type PostSharesRedeemMutationBody = RedeemShareRequest
    export type PostSharesRedeemMutationError = ProblemDetails | void

    /**
 * @summary Redeem a share link as the authenticated caller (join the list).
 */
export const usePostSharesRedeem = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postSharesRedeem>>, TError,{data: RedeemShareRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postSharesRedeem>>,
        TError,
        {data: RedeemShareRequest},
        TContext
      > => {
      return useMutation(getPostSharesRedeemMutationOptions(options), queryClient);
    }
    export const getPostListsListIdSharesUrl = (listId: string,) => {




  return `/lists/${listId}/shares`
}

/**
 * Body `{ access: 'Read' | 'ReadWrite', label?, expiresAt? }`. Returns the opaque token + a ready-to-copy URL. The link grants account-less access at `/shared/{token}` until revoked or expired.
 * @summary Mint a public share link for a list (Owner).
 */
export const postListsListIdShares = async (listId: string,
    createShareRequest: CreateShareRequest, options?: RequestInit): Promise<ShareResponse> => {

  return customFetch<ShareResponse>(getPostListsListIdSharesUrl(listId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createShareRequest)
  }
);}




export const getPostListsListIdSharesMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postListsListIdShares>>, TError,{listId: string;data: CreateShareRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postListsListIdShares>>, TError,{listId: string;data: CreateShareRequest}, TContext> => {

const mutationKey = ['postListsListIdShares'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postListsListIdShares>>, {listId: string;data: CreateShareRequest}> = (props) => {
          const {listId,data} = props ?? {};

          return  postListsListIdShares(listId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostListsListIdSharesMutationResult = NonNullable<Awaited<ReturnType<typeof postListsListIdShares>>>
    export type PostListsListIdSharesMutationBody = CreateShareRequest
    export type PostListsListIdSharesMutationError = ProblemDetails | void

    /**
 * @summary Mint a public share link for a list (Owner).
 */
export const usePostListsListIdShares = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postListsListIdShares>>, TError,{listId: string;data: CreateShareRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postListsListIdShares>>,
        TError,
        {listId: string;data: CreateShareRequest},
        TContext
      > => {
      return useMutation(getPostListsListIdSharesMutationOptions(options), queryClient);
    }
    export const getGetListsListIdSharesUrl = (listId: string,) => {




  return `/lists/${listId}/shares`
}

/**
 * @summary List a list's active share links (Owner).
 */
export const getListsListIdShares = async (listId: string, options?: RequestInit): Promise<ShareCollectionResponse> => {

  return customFetch<ShareCollectionResponse>(getGetListsListIdSharesUrl(listId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetListsListIdSharesQueryKey = (listId: string,) => {
    return [
    `/lists/${listId}/shares`
    ] as const;
    }


export const getGetListsListIdSharesQueryOptions = <TData = Awaited<ReturnType<typeof getListsListIdShares>>, TError = void>(listId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListIdShares>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetListsListIdSharesQueryKey(listId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getListsListIdShares>>> = ({ signal }) => getListsListIdShares(listId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: listId !== null && listId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getListsListIdShares>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetListsListIdSharesQueryResult = NonNullable<Awaited<ReturnType<typeof getListsListIdShares>>>
export type GetListsListIdSharesQueryError = void


export function useGetListsListIdShares<TData = Awaited<ReturnType<typeof getListsListIdShares>>, TError = void>(
 listId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListIdShares>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListsListIdShares>>,
          TError,
          Awaited<ReturnType<typeof getListsListIdShares>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListsListIdShares<TData = Awaited<ReturnType<typeof getListsListIdShares>>, TError = void>(
 listId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListIdShares>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListsListIdShares>>,
          TError,
          Awaited<ReturnType<typeof getListsListIdShares>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListsListIdShares<TData = Awaited<ReturnType<typeof getListsListIdShares>>, TError = void>(
 listId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListIdShares>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List a list's active share links (Owner).
 */

export function useGetListsListIdShares<TData = Awaited<ReturnType<typeof getListsListIdShares>>, TError = void>(
 listId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListIdShares>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetListsListIdSharesQueryOptions(listId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getDeleteListsListIdSharesShareIdUrl = (listId: string,
    shareId: string,) => {




  return `/lists/${listId}/shares/${shareId}`
}

/**
 * @summary Revoke a share link (Owner). The token is rejected on its next use.
 */
export const deleteListsListIdSharesShareId = async (listId: string,
    shareId: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getDeleteListsListIdSharesShareIdUrl(listId,shareId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteListsListIdSharesShareIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteListsListIdSharesShareId>>, TError,{listId: string;shareId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteListsListIdSharesShareId>>, TError,{listId: string;shareId: string}, TContext> => {

const mutationKey = ['deleteListsListIdSharesShareId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteListsListIdSharesShareId>>, {listId: string;shareId: string}> = (props) => {
          const {listId,shareId} = props ?? {};

          return  deleteListsListIdSharesShareId(listId,shareId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteListsListIdSharesShareIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteListsListIdSharesShareId>>>

    export type DeleteListsListIdSharesShareIdMutationError = void

    /**
 * @summary Revoke a share link (Owner). The token is rejected on its next use.
 */
export const useDeleteListsListIdSharesShareId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteListsListIdSharesShareId>>, TError,{listId: string;shareId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteListsListIdSharesShareId>>,
        TError,
        {listId: string;shareId: string},
        TContext
      > => {
      return useMutation(getDeleteListsListIdSharesShareIdMutationOptions(options), queryClient);
    }
