/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Lupira Tasks API
 * Task and command processing backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DirectoryResponse,
  GetUsersDirectoryParams
} from '../models';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetUsersDirectoryUrl = (params?: GetUsersDirectoryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/users/directory?${stringifiedParams}` : `/users/directory`
}

/**
 * `?q=` filters the distinct member emails (case-insensitive substring).
 * @summary People seen across the caller's shared lists (for adding members).
 */
export const getUsersDirectory = async (params?: GetUsersDirectoryParams, options?: RequestInit): Promise<DirectoryResponse> => {

  return customFetch<DirectoryResponse>(getGetUsersDirectoryUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUsersDirectoryQueryKey = (params?: GetUsersDirectoryParams,) => {
    return [
    `/users/directory`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetUsersDirectoryQueryOptions = <TData = Awaited<ReturnType<typeof getUsersDirectory>>, TError = void>(params?: GetUsersDirectoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersDirectory>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersDirectoryQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersDirectory>>> = ({ signal }) => getUsersDirectory(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsersDirectory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersDirectoryQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersDirectory>>>
export type GetUsersDirectoryQueryError = void


export function useGetUsersDirectory<TData = Awaited<ReturnType<typeof getUsersDirectory>>, TError = void>(
 params: undefined |  GetUsersDirectoryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersDirectory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersDirectory>>,
          TError,
          Awaited<ReturnType<typeof getUsersDirectory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersDirectory<TData = Awaited<ReturnType<typeof getUsersDirectory>>, TError = void>(
 params?: GetUsersDirectoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersDirectory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersDirectory>>,
          TError,
          Awaited<ReturnType<typeof getUsersDirectory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersDirectory<TData = Awaited<ReturnType<typeof getUsersDirectory>>, TError = void>(
 params?: GetUsersDirectoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersDirectory>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary People seen across the caller's shared lists (for adding members).
 */

export function useGetUsersDirectory<TData = Awaited<ReturnType<typeof getUsersDirectory>>, TError = void>(
 params?: GetUsersDirectoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersDirectory>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersDirectoryQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






