/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Lupira Tasks API
 * Task and command processing backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetListsListIdSyncParams,
  SyncResponse
} from '../models';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetListsListIdSyncUrl = (listId: string,
    params?: GetListsListIdSyncParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/lists/${listId}/sync?${stringifiedParams}` : `/lists/${listId}/sync`
}

/**
 * Returns the current list plus all its live items (v1 full re-derive,
 * regardless of `?since=`) and a `nextCursor` to pass on the next pull. The
 * client rebases its local mirror onto this base, then re-applies non-acked
 * outbox rows.
 * @summary Offline delta-pull for a list (Viewer+).
 */
export const getListsListIdSync = async (listId: string,
    params?: GetListsListIdSyncParams, options?: RequestInit): Promise<SyncResponse> => {

  return customFetch<SyncResponse>(getGetListsListIdSyncUrl(listId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetListsListIdSyncQueryKey = (listId: string,
    params?: GetListsListIdSyncParams,) => {
    return [
    `/lists/${listId}/sync`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetListsListIdSyncQueryOptions = <TData = Awaited<ReturnType<typeof getListsListIdSync>>, TError = void>(listId: string,
    params?: GetListsListIdSyncParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListIdSync>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetListsListIdSyncQueryKey(listId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getListsListIdSync>>> = ({ signal }) => getListsListIdSync(listId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: listId !== null && listId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getListsListIdSync>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetListsListIdSyncQueryResult = NonNullable<Awaited<ReturnType<typeof getListsListIdSync>>>
export type GetListsListIdSyncQueryError = void


export function useGetListsListIdSync<TData = Awaited<ReturnType<typeof getListsListIdSync>>, TError = void>(
 listId: string,
    params: undefined |  GetListsListIdSyncParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListIdSync>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListsListIdSync>>,
          TError,
          Awaited<ReturnType<typeof getListsListIdSync>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListsListIdSync<TData = Awaited<ReturnType<typeof getListsListIdSync>>, TError = void>(
 listId: string,
    params?: GetListsListIdSyncParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListIdSync>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListsListIdSync>>,
          TError,
          Awaited<ReturnType<typeof getListsListIdSync>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListsListIdSync<TData = Awaited<ReturnType<typeof getListsListIdSync>>, TError = void>(
 listId: string,
    params?: GetListsListIdSyncParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListIdSync>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Offline delta-pull for a list (Viewer+).
 */

export function useGetListsListIdSync<TData = Awaited<ReturnType<typeof getListsListIdSync>>, TError = void>(
 listId: string,
    params?: GetListsListIdSyncParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListIdSync>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetListsListIdSyncQueryOptions(listId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






