/**
 * Generated by orval 🍺
 * Do not edit manually.
 * LupiraTasks BFF
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateItemRequest,
  DeleteSharedItemParams,
  ItemTimestampRequest,
  MoveItemRequest,
  ProblemDetails,
  SharedItemDto,
  SharedListResponse,
  UpdateItemRequest
} from '../models';

import { customFetchShared } from '../../fetcher';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetSharedListUrl = (token: string,) => {




  return `/api/shared/${token}`
}

/**
 * Returns the list + items, trimmed of all emails. `access` indicates read vs read/write.
 * @summary View a shared list by token (no account needed).
 */
export const getSharedList = async (token: string, options?: Parameters<typeof customFetchShared>[1]): Promise<SharedListResponse> => {

  return customFetchShared<SharedListResponse>(getGetSharedListUrl(token),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSharedListQueryKey = (token: string,) => {
    return [
    `/api/shared/${token}`
    ] as const;
    }


export const getGetSharedListQueryOptions = <TData = Awaited<ReturnType<typeof getSharedList>>, TError = ProblemDetails>(token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSharedList>>, TError, TData>>, request?: SecondParameter<typeof customFetchShared>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSharedListQueryKey(token);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSharedList>>> = ({ signal }) => getSharedList(token, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: token !== null && token !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSharedList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSharedListQueryResult = NonNullable<Awaited<ReturnType<typeof getSharedList>>>
export type GetSharedListQueryError = ProblemDetails


export function useGetSharedList<TData = Awaited<ReturnType<typeof getSharedList>>, TError = ProblemDetails>(
 token: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSharedList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSharedList>>,
          TError,
          Awaited<ReturnType<typeof getSharedList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchShared>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSharedList<TData = Awaited<ReturnType<typeof getSharedList>>, TError = ProblemDetails>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSharedList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSharedList>>,
          TError,
          Awaited<ReturnType<typeof getSharedList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchShared>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSharedList<TData = Awaited<ReturnType<typeof getSharedList>>, TError = ProblemDetails>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSharedList>>, TError, TData>>, request?: SecondParameter<typeof customFetchShared>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary View a shared list by token (no account needed).
 */

export function useGetSharedList<TData = Awaited<ReturnType<typeof getSharedList>>, TError = ProblemDetails>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSharedList>>, TError, TData>>, request?: SecondParameter<typeof customFetchShared>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSharedListQueryOptions(token,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getCreateSharedItemUrl = (token: string,) => {




  return `/api/shared/${token}/items`
}

/**
 * @summary Add an item via a read/write share link.
 */
export const createSharedItem = async (token: string,
    createItemRequest: CreateItemRequest, options?: Parameters<typeof customFetchShared>[1]): Promise<SharedItemDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetchShared<SharedItemDto>(getCreateSharedItemUrl(token),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createItemRequest)
  }
);}





export const getCreateSharedItemMutationKey = () => ['createSharedItem'] as const;

export const getCreateSharedItemMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSharedItem>>, TError,CreateSharedItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetchShared>}
): UseMutationOptions<Awaited<ReturnType<typeof createSharedItem>>, TError,CreateSharedItemMutationVariables, TContext> => {

const mutationKey = getCreateSharedItemMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSharedItem>>, CreateSharedItemMutationVariables> = (props) => {
          const {token,data} = props ?? {};

          return  createSharedItem(token,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateSharedItemMutationResult = NonNullable<Awaited<ReturnType<typeof createSharedItem>>>
    export type CreateSharedItemMutationBody = CreateItemRequest
    export type CreateSharedItemMutationError = ProblemDetails
    export type CreateSharedItemMutationVariables = {token: string;data: CreateItemRequest}

    /**
 * @summary Add an item via a read/write share link.
 */
export const useCreateSharedItem = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSharedItem>>, TError,CreateSharedItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetchShared>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createSharedItem>>,
        TError,
        CreateSharedItemMutationVariables,
        TContext
      > => {
      return useMutation(getCreateSharedItemMutationOptions(options), queryClient);
    }
    export const getUpdateSharedItemUrl = (token: string,
    itemId: string,) => {




  return `/api/shared/${token}/items/${itemId}`
}

/**
 * @summary Edit an item via a read/write share link.
 */
export const updateSharedItem = async (token: string,
    itemId: string,
    updateItemRequest: UpdateItemRequest, options?: Parameters<typeof customFetchShared>[1]): Promise<SharedItemDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetchShared<SharedItemDto>(getUpdateSharedItemUrl(token,itemId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateItemRequest)
  }
);}





export const getUpdateSharedItemMutationKey = () => ['updateSharedItem'] as const;

export const getUpdateSharedItemMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSharedItem>>, TError,UpdateSharedItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetchShared>}
): UseMutationOptions<Awaited<ReturnType<typeof updateSharedItem>>, TError,UpdateSharedItemMutationVariables, TContext> => {

const mutationKey = getUpdateSharedItemMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSharedItem>>, UpdateSharedItemMutationVariables> = (props) => {
          const {token,itemId,data} = props ?? {};

          return  updateSharedItem(token,itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateSharedItemMutationResult = NonNullable<Awaited<ReturnType<typeof updateSharedItem>>>
    export type UpdateSharedItemMutationBody = UpdateItemRequest
    export type UpdateSharedItemMutationError = ProblemDetails
    export type UpdateSharedItemMutationVariables = {token: string;itemId: string;data: UpdateItemRequest}

    /**
 * @summary Edit an item via a read/write share link.
 */
export const useUpdateSharedItem = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSharedItem>>, TError,UpdateSharedItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetchShared>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSharedItem>>,
        TError,
        UpdateSharedItemMutationVariables,
        TContext
      > => {
      return useMutation(getUpdateSharedItemMutationOptions(options), queryClient);
    }
    export const getDeleteSharedItemUrl = (token: string,
    itemId: string,
    params?: DeleteSharedItemParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/shared/${token}/items/${itemId}?${stringifiedParams}` : `/api/shared/${token}/items/${itemId}`
}

/**
 * @summary Delete an item via a read/write share link.
 */
export const deleteSharedItem = async (token: string,
    itemId: string,
    params?: DeleteSharedItemParams, options?: Parameters<typeof customFetchShared>[1]): Promise<void> => {

  return customFetchShared<void>(getDeleteSharedItemUrl(token,itemId,params),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteSharedItemMutationKey = () => ['deleteSharedItem'] as const;

export const getDeleteSharedItemMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSharedItem>>, TError,DeleteSharedItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetchShared>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteSharedItem>>, TError,DeleteSharedItemMutationVariables, TContext> => {

const mutationKey = getDeleteSharedItemMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSharedItem>>, DeleteSharedItemMutationVariables> = (props) => {
          const {token,itemId,params} = props ?? {};

          return  deleteSharedItem(token,itemId,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteSharedItemMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSharedItem>>>

    export type DeleteSharedItemMutationError = ProblemDetails
    export type DeleteSharedItemMutationVariables = {token: string;itemId: string;params?: DeleteSharedItemParams}

    /**
 * @summary Delete an item via a read/write share link.
 */
export const useDeleteSharedItem = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSharedItem>>, TError,DeleteSharedItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetchShared>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteSharedItem>>,
        TError,
        DeleteSharedItemMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteSharedItemMutationOptions(options), queryClient);
    }
    export const getCompleteSharedItemUrl = (token: string,
    itemId: string,) => {




  return `/api/shared/${token}/items/${itemId}/complete`
}

/**
 * @summary Mark an item complete via a read/write share link.
 */
export const completeSharedItem = async (token: string,
    itemId: string,
    nullItemTimestampRequest?: null | ItemTimestampRequest, options?: Parameters<typeof customFetchShared>[1]): Promise<SharedItemDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetchShared<SharedItemDto>(getCompleteSharedItemUrl(token,itemId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(nullItemTimestampRequest)
  }
);}





export const getCompleteSharedItemMutationKey = () => ['completeSharedItem'] as const;

export const getCompleteSharedItemMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeSharedItem>>, TError,CompleteSharedItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetchShared>}
): UseMutationOptions<Awaited<ReturnType<typeof completeSharedItem>>, TError,CompleteSharedItemMutationVariables, TContext> => {

const mutationKey = getCompleteSharedItemMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof completeSharedItem>>, CompleteSharedItemMutationVariables> = (props) => {
          const {token,itemId,data} = props ?? {};

          return  completeSharedItem(token,itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CompleteSharedItemMutationResult = NonNullable<Awaited<ReturnType<typeof completeSharedItem>>>
    export type CompleteSharedItemMutationBody = null | ItemTimestampRequest | undefined
    export type CompleteSharedItemMutationError = ProblemDetails
    export type CompleteSharedItemMutationVariables = {token: string;itemId: string;data?: null | ItemTimestampRequest}

    /**
 * @summary Mark an item complete via a read/write share link.
 */
export const useCompleteSharedItem = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeSharedItem>>, TError,CompleteSharedItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetchShared>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof completeSharedItem>>,
        TError,
        CompleteSharedItemMutationVariables,
        TContext
      > => {
      return useMutation(getCompleteSharedItemMutationOptions(options), queryClient);
    }
    export const getMoveSharedItemUrl = (token: string,
    itemId: string,) => {




  return `/api/shared/${token}/items/${itemId}/move`
}

/**
 * @summary Reparent / reorder an item via a read/write share link.
 */
export const moveSharedItem = async (token: string,
    itemId: string,
    moveItemRequest: MoveItemRequest, options?: Parameters<typeof customFetchShared>[1]): Promise<SharedItemDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetchShared<SharedItemDto>(getMoveSharedItemUrl(token,itemId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(moveItemRequest)
  }
);}





export const getMoveSharedItemMutationKey = () => ['moveSharedItem'] as const;

export const getMoveSharedItemMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof moveSharedItem>>, TError,MoveSharedItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetchShared>}
): UseMutationOptions<Awaited<ReturnType<typeof moveSharedItem>>, TError,MoveSharedItemMutationVariables, TContext> => {

const mutationKey = getMoveSharedItemMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof moveSharedItem>>, MoveSharedItemMutationVariables> = (props) => {
          const {token,itemId,data} = props ?? {};

          return  moveSharedItem(token,itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MoveSharedItemMutationResult = NonNullable<Awaited<ReturnType<typeof moveSharedItem>>>
    export type MoveSharedItemMutationBody = MoveItemRequest
    export type MoveSharedItemMutationError = ProblemDetails
    export type MoveSharedItemMutationVariables = {token: string;itemId: string;data: MoveItemRequest}

    /**
 * @summary Reparent / reorder an item via a read/write share link.
 */
export const useMoveSharedItem = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof moveSharedItem>>, TError,MoveSharedItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetchShared>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof moveSharedItem>>,
        TError,
        MoveSharedItemMutationVariables,
        TContext
      > => {
      return useMutation(getMoveSharedItemMutationOptions(options), queryClient);
    }
    export const getReopenSharedItemUrl = (token: string,
    itemId: string,) => {




  return `/api/shared/${token}/items/${itemId}/reopen`
}

/**
 * @summary Reopen a completed item via a read/write share link.
 */
export const reopenSharedItem = async (token: string,
    itemId: string,
    nullItemTimestampRequest?: null | ItemTimestampRequest, options?: Parameters<typeof customFetchShared>[1]): Promise<SharedItemDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetchShared<SharedItemDto>(getReopenSharedItemUrl(token,itemId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(nullItemTimestampRequest)
  }
);}





export const getReopenSharedItemMutationKey = () => ['reopenSharedItem'] as const;

export const getReopenSharedItemMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reopenSharedItem>>, TError,ReopenSharedItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetchShared>}
): UseMutationOptions<Awaited<ReturnType<typeof reopenSharedItem>>, TError,ReopenSharedItemMutationVariables, TContext> => {

const mutationKey = getReopenSharedItemMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reopenSharedItem>>, ReopenSharedItemMutationVariables> = (props) => {
          const {token,itemId,data} = props ?? {};

          return  reopenSharedItem(token,itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ReopenSharedItemMutationResult = NonNullable<Awaited<ReturnType<typeof reopenSharedItem>>>
    export type ReopenSharedItemMutationBody = null | ItemTimestampRequest | undefined
    export type ReopenSharedItemMutationError = ProblemDetails
    export type ReopenSharedItemMutationVariables = {token: string;itemId: string;data?: null | ItemTimestampRequest}

    /**
 * @summary Reopen a completed item via a read/write share link.
 */
export const useReopenSharedItem = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reopenSharedItem>>, TError,ReopenSharedItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetchShared>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reopenSharedItem>>,
        TError,
        ReopenSharedItemMutationVariables,
        TContext
      > => {
      return useMutation(getReopenSharedItemMutationOptions(options), queryClient);
    }
