/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Lupira Tasks API
 * Task and command processing backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateItemRequest,
  DeleteSharedTokenItemsItemIdParams,
  ItemTimestampRequest,
  MoveItemRequest,
  ProblemDetails,
  SharedItemResponse,
  SharedListResponse,
  UpdateItemRequest
} from '../models';

import { customFetchShared } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetSharedTokenUrl = (token: string,) => {




  return `/shared/${token}`
}

/**
 * Returns the list + items, trimmed of all emails. `access` indicates read vs read/write.
 * @summary View a shared list by token (no account needed).
 */
export const getSharedToken = async (token: string, options?: RequestInit): Promise<SharedListResponse> => {

  return customFetchShared<SharedListResponse>(getGetSharedTokenUrl(token),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSharedTokenQueryKey = (token: string,) => {
    return [
    `/shared/${token}`
    ] as const;
    }


export const getGetSharedTokenQueryOptions = <TData = Awaited<ReturnType<typeof getSharedToken>>, TError = void>(token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSharedToken>>, TError, TData>>, request?: SecondParameter<typeof customFetchShared>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSharedTokenQueryKey(token);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSharedToken>>> = ({ signal }) => getSharedToken(token, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: token !== null && token !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSharedToken>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSharedTokenQueryResult = NonNullable<Awaited<ReturnType<typeof getSharedToken>>>
export type GetSharedTokenQueryError = void


export function useGetSharedToken<TData = Awaited<ReturnType<typeof getSharedToken>>, TError = void>(
 token: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSharedToken>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSharedToken>>,
          TError,
          Awaited<ReturnType<typeof getSharedToken>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchShared>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSharedToken<TData = Awaited<ReturnType<typeof getSharedToken>>, TError = void>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSharedToken>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSharedToken>>,
          TError,
          Awaited<ReturnType<typeof getSharedToken>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchShared>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSharedToken<TData = Awaited<ReturnType<typeof getSharedToken>>, TError = void>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSharedToken>>, TError, TData>>, request?: SecondParameter<typeof customFetchShared>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary View a shared list by token (no account needed).
 */

export function useGetSharedToken<TData = Awaited<ReturnType<typeof getSharedToken>>, TError = void>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSharedToken>>, TError, TData>>, request?: SecondParameter<typeof customFetchShared>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSharedTokenQueryOptions(token,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPostSharedTokenItemsUrl = (token: string,) => {




  return `/shared/${token}/items`
}

/**
 * @summary Add an item via a read/write share link.
 */
export const postSharedTokenItems = async (token: string,
    createItemRequest: CreateItemRequest, options?: RequestInit): Promise<SharedItemResponse> => {

  return customFetchShared<SharedItemResponse>(getPostSharedTokenItemsUrl(token),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createItemRequest)
  }
);}




export const getPostSharedTokenItemsMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postSharedTokenItems>>, TError,{token: string;data: CreateItemRequest}, TContext>, request?: SecondParameter<typeof customFetchShared>}
): UseMutationOptions<Awaited<ReturnType<typeof postSharedTokenItems>>, TError,{token: string;data: CreateItemRequest}, TContext> => {

const mutationKey = ['postSharedTokenItems'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postSharedTokenItems>>, {token: string;data: CreateItemRequest}> = (props) => {
          const {token,data} = props ?? {};

          return  postSharedTokenItems(token,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostSharedTokenItemsMutationResult = NonNullable<Awaited<ReturnType<typeof postSharedTokenItems>>>
    export type PostSharedTokenItemsMutationBody = CreateItemRequest
    export type PostSharedTokenItemsMutationError = ProblemDetails | void

    /**
 * @summary Add an item via a read/write share link.
 */
export const usePostSharedTokenItems = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postSharedTokenItems>>, TError,{token: string;data: CreateItemRequest}, TContext>, request?: SecondParameter<typeof customFetchShared>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postSharedTokenItems>>,
        TError,
        {token: string;data: CreateItemRequest},
        TContext
      > => {
      return useMutation(getPostSharedTokenItemsMutationOptions(options), queryClient);
    }
    export const getPatchSharedTokenItemsItemIdUrl = (token: string,
    itemId: string,) => {




  return `/shared/${token}/items/${itemId}`
}

/**
 * @summary Edit an item via a read/write share link.
 */
export const patchSharedTokenItemsItemId = async (token: string,
    itemId: string,
    updateItemRequest: UpdateItemRequest, options?: RequestInit): Promise<SharedItemResponse> => {

  return customFetchShared<SharedItemResponse>(getPatchSharedTokenItemsItemIdUrl(token,itemId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateItemRequest)
  }
);}




export const getPatchSharedTokenItemsItemIdMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchSharedTokenItemsItemId>>, TError,{token: string;itemId: string;data: UpdateItemRequest}, TContext>, request?: SecondParameter<typeof customFetchShared>}
): UseMutationOptions<Awaited<ReturnType<typeof patchSharedTokenItemsItemId>>, TError,{token: string;itemId: string;data: UpdateItemRequest}, TContext> => {

const mutationKey = ['patchSharedTokenItemsItemId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchSharedTokenItemsItemId>>, {token: string;itemId: string;data: UpdateItemRequest}> = (props) => {
          const {token,itemId,data} = props ?? {};

          return  patchSharedTokenItemsItemId(token,itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchSharedTokenItemsItemIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchSharedTokenItemsItemId>>>
    export type PatchSharedTokenItemsItemIdMutationBody = UpdateItemRequest
    export type PatchSharedTokenItemsItemIdMutationError = ProblemDetails | void

    /**
 * @summary Edit an item via a read/write share link.
 */
export const usePatchSharedTokenItemsItemId = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchSharedTokenItemsItemId>>, TError,{token: string;itemId: string;data: UpdateItemRequest}, TContext>, request?: SecondParameter<typeof customFetchShared>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchSharedTokenItemsItemId>>,
        TError,
        {token: string;itemId: string;data: UpdateItemRequest},
        TContext
      > => {
      return useMutation(getPatchSharedTokenItemsItemIdMutationOptions(options), queryClient);
    }
    export const getDeleteSharedTokenItemsItemIdUrl = (token: string,
    itemId: string,
    params?: DeleteSharedTokenItemsItemIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/shared/${token}/items/${itemId}?${stringifiedParams}` : `/shared/${token}/items/${itemId}`
}

/**
 * @summary Delete an item via a read/write share link.
 */
export const deleteSharedTokenItemsItemId = async (token: string,
    itemId: string,
    params?: DeleteSharedTokenItemsItemIdParams, options?: RequestInit): Promise<void> => {

  return customFetchShared<void>(getDeleteSharedTokenItemsItemIdUrl(token,itemId,params),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteSharedTokenItemsItemIdMutationOptions = <TError = void | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSharedTokenItemsItemId>>, TError,{token: string;itemId: string;params?: DeleteSharedTokenItemsItemIdParams}, TContext>, request?: SecondParameter<typeof customFetchShared>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteSharedTokenItemsItemId>>, TError,{token: string;itemId: string;params?: DeleteSharedTokenItemsItemIdParams}, TContext> => {

const mutationKey = ['deleteSharedTokenItemsItemId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSharedTokenItemsItemId>>, {token: string;itemId: string;params?: DeleteSharedTokenItemsItemIdParams}> = (props) => {
          const {token,itemId,params} = props ?? {};

          return  deleteSharedTokenItemsItemId(token,itemId,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteSharedTokenItemsItemIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSharedTokenItemsItemId>>>

    export type DeleteSharedTokenItemsItemIdMutationError = void | ProblemDetails

    /**
 * @summary Delete an item via a read/write share link.
 */
export const useDeleteSharedTokenItemsItemId = <TError = void | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSharedTokenItemsItemId>>, TError,{token: string;itemId: string;params?: DeleteSharedTokenItemsItemIdParams}, TContext>, request?: SecondParameter<typeof customFetchShared>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteSharedTokenItemsItemId>>,
        TError,
        {token: string;itemId: string;params?: DeleteSharedTokenItemsItemIdParams},
        TContext
      > => {
      return useMutation(getDeleteSharedTokenItemsItemIdMutationOptions(options), queryClient);
    }
    export const getPostSharedTokenItemsItemIdCompleteUrl = (token: string,
    itemId: string,) => {




  return `/shared/${token}/items/${itemId}/complete`
}

/**
 * @summary Mark an item complete via a read/write share link.
 */
export const postSharedTokenItemsItemIdComplete = async (token: string,
    itemId: string,
    nullItemTimestampRequest?: null | ItemTimestampRequest, options?: RequestInit): Promise<SharedItemResponse> => {

  return customFetchShared<SharedItemResponse>(getPostSharedTokenItemsItemIdCompleteUrl(token,itemId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(nullItemTimestampRequest)
  }
);}




export const getPostSharedTokenItemsItemIdCompleteMutationOptions = <TError = void | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postSharedTokenItemsItemIdComplete>>, TError,{token: string;itemId: string;data?: null | ItemTimestampRequest}, TContext>, request?: SecondParameter<typeof customFetchShared>}
): UseMutationOptions<Awaited<ReturnType<typeof postSharedTokenItemsItemIdComplete>>, TError,{token: string;itemId: string;data?: null | ItemTimestampRequest}, TContext> => {

const mutationKey = ['postSharedTokenItemsItemIdComplete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postSharedTokenItemsItemIdComplete>>, {token: string;itemId: string;data?: null | ItemTimestampRequest}> = (props) => {
          const {token,itemId,data} = props ?? {};

          return  postSharedTokenItemsItemIdComplete(token,itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostSharedTokenItemsItemIdCompleteMutationResult = NonNullable<Awaited<ReturnType<typeof postSharedTokenItemsItemIdComplete>>>
    export type PostSharedTokenItemsItemIdCompleteMutationBody = null | ItemTimestampRequest | undefined
    export type PostSharedTokenItemsItemIdCompleteMutationError = void | ProblemDetails

    /**
 * @summary Mark an item complete via a read/write share link.
 */
export const usePostSharedTokenItemsItemIdComplete = <TError = void | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postSharedTokenItemsItemIdComplete>>, TError,{token: string;itemId: string;data?: null | ItemTimestampRequest}, TContext>, request?: SecondParameter<typeof customFetchShared>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postSharedTokenItemsItemIdComplete>>,
        TError,
        {token: string;itemId: string;data?: null | ItemTimestampRequest},
        TContext
      > => {
      return useMutation(getPostSharedTokenItemsItemIdCompleteMutationOptions(options), queryClient);
    }
    export const getPostSharedTokenItemsItemIdReopenUrl = (token: string,
    itemId: string,) => {




  return `/shared/${token}/items/${itemId}/reopen`
}

/**
 * @summary Reopen a completed item via a read/write share link.
 */
export const postSharedTokenItemsItemIdReopen = async (token: string,
    itemId: string,
    nullItemTimestampRequest?: null | ItemTimestampRequest, options?: RequestInit): Promise<SharedItemResponse> => {

  return customFetchShared<SharedItemResponse>(getPostSharedTokenItemsItemIdReopenUrl(token,itemId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(nullItemTimestampRequest)
  }
);}




export const getPostSharedTokenItemsItemIdReopenMutationOptions = <TError = void | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postSharedTokenItemsItemIdReopen>>, TError,{token: string;itemId: string;data?: null | ItemTimestampRequest}, TContext>, request?: SecondParameter<typeof customFetchShared>}
): UseMutationOptions<Awaited<ReturnType<typeof postSharedTokenItemsItemIdReopen>>, TError,{token: string;itemId: string;data?: null | ItemTimestampRequest}, TContext> => {

const mutationKey = ['postSharedTokenItemsItemIdReopen'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postSharedTokenItemsItemIdReopen>>, {token: string;itemId: string;data?: null | ItemTimestampRequest}> = (props) => {
          const {token,itemId,data} = props ?? {};

          return  postSharedTokenItemsItemIdReopen(token,itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostSharedTokenItemsItemIdReopenMutationResult = NonNullable<Awaited<ReturnType<typeof postSharedTokenItemsItemIdReopen>>>
    export type PostSharedTokenItemsItemIdReopenMutationBody = null | ItemTimestampRequest | undefined
    export type PostSharedTokenItemsItemIdReopenMutationError = void | ProblemDetails

    /**
 * @summary Reopen a completed item via a read/write share link.
 */
export const usePostSharedTokenItemsItemIdReopen = <TError = void | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postSharedTokenItemsItemIdReopen>>, TError,{token: string;itemId: string;data?: null | ItemTimestampRequest}, TContext>, request?: SecondParameter<typeof customFetchShared>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postSharedTokenItemsItemIdReopen>>,
        TError,
        {token: string;itemId: string;data?: null | ItemTimestampRequest},
        TContext
      > => {
      return useMutation(getPostSharedTokenItemsItemIdReopenMutationOptions(options), queryClient);
    }
    export const getPostSharedTokenItemsItemIdMoveUrl = (token: string,
    itemId: string,) => {




  return `/shared/${token}/items/${itemId}/move`
}

/**
 * @summary Reparent / reorder an item via a read/write share link.
 */
export const postSharedTokenItemsItemIdMove = async (token: string,
    itemId: string,
    moveItemRequest: MoveItemRequest, options?: RequestInit): Promise<SharedItemResponse> => {

  return customFetchShared<SharedItemResponse>(getPostSharedTokenItemsItemIdMoveUrl(token,itemId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(moveItemRequest)
  }
);}




export const getPostSharedTokenItemsItemIdMoveMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postSharedTokenItemsItemIdMove>>, TError,{token: string;itemId: string;data: MoveItemRequest}, TContext>, request?: SecondParameter<typeof customFetchShared>}
): UseMutationOptions<Awaited<ReturnType<typeof postSharedTokenItemsItemIdMove>>, TError,{token: string;itemId: string;data: MoveItemRequest}, TContext> => {

const mutationKey = ['postSharedTokenItemsItemIdMove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postSharedTokenItemsItemIdMove>>, {token: string;itemId: string;data: MoveItemRequest}> = (props) => {
          const {token,itemId,data} = props ?? {};

          return  postSharedTokenItemsItemIdMove(token,itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostSharedTokenItemsItemIdMoveMutationResult = NonNullable<Awaited<ReturnType<typeof postSharedTokenItemsItemIdMove>>>
    export type PostSharedTokenItemsItemIdMoveMutationBody = MoveItemRequest
    export type PostSharedTokenItemsItemIdMoveMutationError = ProblemDetails | void

    /**
 * @summary Reparent / reorder an item via a read/write share link.
 */
export const usePostSharedTokenItemsItemIdMove = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postSharedTokenItemsItemIdMove>>, TError,{token: string;itemId: string;data: MoveItemRequest}, TContext>, request?: SecondParameter<typeof customFetchShared>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postSharedTokenItemsItemIdMove>>,
        TError,
        {token: string;itemId: string;data: MoveItemRequest},
        TContext
      > => {
      return useMutation(getPostSharedTokenItemsItemIdMoveMutationOptions(options), queryClient);
    }
