/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Lupira Tasks API
 * Task and command processing backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateItemRequest,
  DeleteListsListIdItemsItemIdParams,
  GetItemsParams,
  GetListsListIdItemsParams,
  ItemCollectionResponse,
  ItemResponse,
  ItemTimestampRequest,
  MoveItemRequest,
  ProblemDetails,
  SetMetadataRequest,
  SetStatusRequest,
  UpdateItemRequest
} from '../models';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetItemsUrl = (params?: GetItemsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/items?${stringifiedParams}` : `/items`
}

/**
 * Case-insensitive `query` title substring, optional `completed`/`status`. Spans every list the caller is a member of (archived included).
 * @summary Search items across the caller's lists (Viewer+).
 */
export const getItems = async (params?: GetItemsParams, options?: RequestInit): Promise<ItemCollectionResponse> => {

  return customFetch<ItemCollectionResponse>(getGetItemsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetItemsQueryKey = (params?: GetItemsParams,) => {
    return [
    `/items`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetItemsQueryOptions = <TData = Awaited<ReturnType<typeof getItems>>, TError = void>(params?: GetItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetItemsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getItems>>> = ({ signal }) => getItems(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetItemsQueryResult = NonNullable<Awaited<ReturnType<typeof getItems>>>
export type GetItemsQueryError = void


export function useGetItems<TData = Awaited<ReturnType<typeof getItems>>, TError = void>(
 params: undefined |  GetItemsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItems>>,
          TError,
          Awaited<ReturnType<typeof getItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItems<TData = Awaited<ReturnType<typeof getItems>>, TError = void>(
 params?: GetItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItems>>,
          TError,
          Awaited<ReturnType<typeof getItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItems<TData = Awaited<ReturnType<typeof getItems>>, TError = void>(
 params?: GetItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search items across the caller's lists (Viewer+).
 */

export function useGetItems<TData = Awaited<ReturnType<typeof getItems>>, TError = void>(
 params?: GetItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetItemsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPatchItemsItemIdUrl = (itemId: string,) => {




  return `/items/${itemId}`
}

/**
 * Same body as the list-scoped PATCH (`*Provided` flags). 404 if no such item or the caller can't edit its list.
 * @summary Edit item fields addressed by id (Editor+); the list is resolved server-side.
 */
export const patchItemsItemId = async (itemId: string,
    updateItemRequest: UpdateItemRequest, options?: RequestInit): Promise<ItemResponse> => {

  return customFetch<ItemResponse>(getPatchItemsItemIdUrl(itemId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateItemRequest)
  }
);}




export const getPatchItemsItemIdMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchItemsItemId>>, TError,{itemId: string;data: UpdateItemRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof patchItemsItemId>>, TError,{itemId: string;data: UpdateItemRequest}, TContext> => {

const mutationKey = ['patchItemsItemId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchItemsItemId>>, {itemId: string;data: UpdateItemRequest}> = (props) => {
          const {itemId,data} = props ?? {};

          return  patchItemsItemId(itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchItemsItemIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchItemsItemId>>>
    export type PatchItemsItemIdMutationBody = UpdateItemRequest
    export type PatchItemsItemIdMutationError = ProblemDetails | void

    /**
 * @summary Edit item fields addressed by id (Editor+); the list is resolved server-side.
 */
export const usePatchItemsItemId = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchItemsItemId>>, TError,{itemId: string;data: UpdateItemRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchItemsItemId>>,
        TError,
        {itemId: string;data: UpdateItemRequest},
        TContext
      > => {
      return useMutation(getPatchItemsItemIdMutationOptions(options), queryClient);
    }
    export const getPostItemsItemIdMetadataUrl = (itemId: string,) => {




  return `/items/${itemId}/metadata`
}

/**
 * Body `{ metadata (JSON object or null), occurredAt? }`. Whole-field LWW. 404 if no such item or the caller can't edit its list.
 * @summary Set an item's metadata addressed by id (Editor+); the list is resolved server-side.
 */
export const postItemsItemIdMetadata = async (itemId: string,
    setMetadataRequest: SetMetadataRequest, options?: RequestInit): Promise<ItemResponse> => {

  return customFetch<ItemResponse>(getPostItemsItemIdMetadataUrl(itemId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(setMetadataRequest)
  }
);}




export const getPostItemsItemIdMetadataMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postItemsItemIdMetadata>>, TError,{itemId: string;data: SetMetadataRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postItemsItemIdMetadata>>, TError,{itemId: string;data: SetMetadataRequest}, TContext> => {

const mutationKey = ['postItemsItemIdMetadata'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postItemsItemIdMetadata>>, {itemId: string;data: SetMetadataRequest}> = (props) => {
          const {itemId,data} = props ?? {};

          return  postItemsItemIdMetadata(itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostItemsItemIdMetadataMutationResult = NonNullable<Awaited<ReturnType<typeof postItemsItemIdMetadata>>>
    export type PostItemsItemIdMetadataMutationBody = SetMetadataRequest
    export type PostItemsItemIdMetadataMutationError = ProblemDetails | void

    /**
 * @summary Set an item's metadata addressed by id (Editor+); the list is resolved server-side.
 */
export const usePostItemsItemIdMetadata = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postItemsItemIdMetadata>>, TError,{itemId: string;data: SetMetadataRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postItemsItemIdMetadata>>,
        TError,
        {itemId: string;data: SetMetadataRequest},
        TContext
      > => {
      return useMutation(getPostItemsItemIdMetadataMutationOptions(options), queryClient);
    }
    export const getGetListsListIdItemsUrl = (listId: string,
    params?: GetListsListIdItemsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/lists/${listId}/items?${stringifiedParams}` : `/lists/${listId}/items`
}

/**
 * Excludes deleted items; ordered by `sortOrder`. Filters: `completed`, `tagId`, `parentItemId`, `assignedTo`, `status`.
 * @summary List a list's items (Viewer+).
 */
export const getListsListIdItems = async (listId: string,
    params?: GetListsListIdItemsParams, options?: RequestInit): Promise<ItemCollectionResponse> => {

  return customFetch<ItemCollectionResponse>(getGetListsListIdItemsUrl(listId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetListsListIdItemsQueryKey = (listId: string,
    params?: GetListsListIdItemsParams,) => {
    return [
    `/lists/${listId}/items`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetListsListIdItemsQueryOptions = <TData = Awaited<ReturnType<typeof getListsListIdItems>>, TError = void>(listId: string,
    params?: GetListsListIdItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListIdItems>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetListsListIdItemsQueryKey(listId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getListsListIdItems>>> = ({ signal }) => getListsListIdItems(listId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: listId !== null && listId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getListsListIdItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetListsListIdItemsQueryResult = NonNullable<Awaited<ReturnType<typeof getListsListIdItems>>>
export type GetListsListIdItemsQueryError = void


export function useGetListsListIdItems<TData = Awaited<ReturnType<typeof getListsListIdItems>>, TError = void>(
 listId: string,
    params: undefined |  GetListsListIdItemsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListIdItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListsListIdItems>>,
          TError,
          Awaited<ReturnType<typeof getListsListIdItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListsListIdItems<TData = Awaited<ReturnType<typeof getListsListIdItems>>, TError = void>(
 listId: string,
    params?: GetListsListIdItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListIdItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListsListIdItems>>,
          TError,
          Awaited<ReturnType<typeof getListsListIdItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListsListIdItems<TData = Awaited<ReturnType<typeof getListsListIdItems>>, TError = void>(
 listId: string,
    params?: GetListsListIdItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListIdItems>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List a list's items (Viewer+).
 */

export function useGetListsListIdItems<TData = Awaited<ReturnType<typeof getListsListIdItems>>, TError = void>(
 listId: string,
    params?: GetListsListIdItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListIdItems>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetListsListIdItemsQueryOptions(listId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPostListsListIdItemsUrl = (listId: string,) => {




  return `/lists/${listId}/items`
}

/**
 * Body `{ id (GUIDv7), title, parentItemId?, dueAt?, assigneeEmail?, quantity?, unit?, priority? (0..9), tagIds?, sortOrder, occurredAt? }`. Re-sending an existing id is idempotent.
 * @summary Add an item (Editor+).
 */
export const postListsListIdItems = async (listId: string,
    createItemRequest: CreateItemRequest, options?: RequestInit): Promise<ItemResponse> => {

  return customFetch<ItemResponse>(getPostListsListIdItemsUrl(listId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createItemRequest)
  }
);}




export const getPostListsListIdItemsMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postListsListIdItems>>, TError,{listId: string;data: CreateItemRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postListsListIdItems>>, TError,{listId: string;data: CreateItemRequest}, TContext> => {

const mutationKey = ['postListsListIdItems'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postListsListIdItems>>, {listId: string;data: CreateItemRequest}> = (props) => {
          const {listId,data} = props ?? {};

          return  postListsListIdItems(listId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostListsListIdItemsMutationResult = NonNullable<Awaited<ReturnType<typeof postListsListIdItems>>>
    export type PostListsListIdItemsMutationBody = CreateItemRequest
    export type PostListsListIdItemsMutationError = ProblemDetails | void

    /**
 * @summary Add an item (Editor+).
 */
export const usePostListsListIdItems = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postListsListIdItems>>, TError,{listId: string;data: CreateItemRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postListsListIdItems>>,
        TError,
        {listId: string;data: CreateItemRequest},
        TContext
      > => {
      return useMutation(getPostListsListIdItemsMutationOptions(options), queryClient);
    }
    export const getGetListsListIdItemsItemIdUrl = (listId: string,
    itemId: string,) => {




  return `/lists/${listId}/items/${itemId}`
}

/**
 * @summary Get a single item (Viewer+).
 */
export const getListsListIdItemsItemId = async (listId: string,
    itemId: string, options?: RequestInit): Promise<ItemResponse> => {

  return customFetch<ItemResponse>(getGetListsListIdItemsItemIdUrl(listId,itemId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetListsListIdItemsItemIdQueryKey = (listId: string,
    itemId: string,) => {
    return [
    `/lists/${listId}/items/${itemId}`
    ] as const;
    }


export const getGetListsListIdItemsItemIdQueryOptions = <TData = Awaited<ReturnType<typeof getListsListIdItemsItemId>>, TError = void>(listId: string,
    itemId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListIdItemsItemId>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetListsListIdItemsItemIdQueryKey(listId,itemId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getListsListIdItemsItemId>>> = ({ signal }) => getListsListIdItemsItemId(listId,itemId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: listId !== null && listId !== undefined && itemId !== null && itemId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getListsListIdItemsItemId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetListsListIdItemsItemIdQueryResult = NonNullable<Awaited<ReturnType<typeof getListsListIdItemsItemId>>>
export type GetListsListIdItemsItemIdQueryError = void


export function useGetListsListIdItemsItemId<TData = Awaited<ReturnType<typeof getListsListIdItemsItemId>>, TError = void>(
 listId: string,
    itemId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListIdItemsItemId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListsListIdItemsItemId>>,
          TError,
          Awaited<ReturnType<typeof getListsListIdItemsItemId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListsListIdItemsItemId<TData = Awaited<ReturnType<typeof getListsListIdItemsItemId>>, TError = void>(
 listId: string,
    itemId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListIdItemsItemId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListsListIdItemsItemId>>,
          TError,
          Awaited<ReturnType<typeof getListsListIdItemsItemId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListsListIdItemsItemId<TData = Awaited<ReturnType<typeof getListsListIdItemsItemId>>, TError = void>(
 listId: string,
    itemId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListIdItemsItemId>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a single item (Viewer+).
 */

export function useGetListsListIdItemsItemId<TData = Awaited<ReturnType<typeof getListsListIdItemsItemId>>, TError = void>(
 listId: string,
    itemId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListIdItemsItemId>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetListsListIdItemsItemIdQueryOptions(listId,itemId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPatchListsListIdItemsItemIdUrl = (listId: string,
    itemId: string,) => {




  return `/lists/${listId}/items/${itemId}`
}

/**
 * One event per changed field. Use the `*Provided` flags so a null can mean 'clear' rather than 'unchanged' (e.g. `priority` 0..9 with `priorityProvided`). Tags via `addTagIds`/`removeTagIds`.
 * @summary Edit item fields (Editor+).
 */
export const patchListsListIdItemsItemId = async (listId: string,
    itemId: string,
    updateItemRequest: UpdateItemRequest, options?: RequestInit): Promise<ItemResponse> => {

  return customFetch<ItemResponse>(getPatchListsListIdItemsItemIdUrl(listId,itemId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateItemRequest)
  }
);}




export const getPatchListsListIdItemsItemIdMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchListsListIdItemsItemId>>, TError,{listId: string;itemId: string;data: UpdateItemRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof patchListsListIdItemsItemId>>, TError,{listId: string;itemId: string;data: UpdateItemRequest}, TContext> => {

const mutationKey = ['patchListsListIdItemsItemId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchListsListIdItemsItemId>>, {listId: string;itemId: string;data: UpdateItemRequest}> = (props) => {
          const {listId,itemId,data} = props ?? {};

          return  patchListsListIdItemsItemId(listId,itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchListsListIdItemsItemIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchListsListIdItemsItemId>>>
    export type PatchListsListIdItemsItemIdMutationBody = UpdateItemRequest
    export type PatchListsListIdItemsItemIdMutationError = ProblemDetails | void

    /**
 * @summary Edit item fields (Editor+).
 */
export const usePatchListsListIdItemsItemId = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchListsListIdItemsItemId>>, TError,{listId: string;itemId: string;data: UpdateItemRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchListsListIdItemsItemId>>,
        TError,
        {listId: string;itemId: string;data: UpdateItemRequest},
        TContext
      > => {
      return useMutation(getPatchListsListIdItemsItemIdMutationOptions(options), queryClient);
    }
    export const getDeleteListsListIdItemsItemIdUrl = (listId: string,
    itemId: string,
    params?: DeleteListsListIdItemsItemIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/lists/${listId}/items/${itemId}?${stringifiedParams}` : `/lists/${listId}/items/${itemId}`
}

/**
 * Optional `?occurredAt=` (ISO-8601) carries the client timestamp for LWW.
 * @summary Delete an item (Editor+). Tombstone.
 */
export const deleteListsListIdItemsItemId = async (listId: string,
    itemId: string,
    params?: DeleteListsListIdItemsItemIdParams, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getDeleteListsListIdItemsItemIdUrl(listId,itemId,params),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteListsListIdItemsItemIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteListsListIdItemsItemId>>, TError,{listId: string;itemId: string;params?: DeleteListsListIdItemsItemIdParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteListsListIdItemsItemId>>, TError,{listId: string;itemId: string;params?: DeleteListsListIdItemsItemIdParams}, TContext> => {

const mutationKey = ['deleteListsListIdItemsItemId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteListsListIdItemsItemId>>, {listId: string;itemId: string;params?: DeleteListsListIdItemsItemIdParams}> = (props) => {
          const {listId,itemId,params} = props ?? {};

          return  deleteListsListIdItemsItemId(listId,itemId,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteListsListIdItemsItemIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteListsListIdItemsItemId>>>

    export type DeleteListsListIdItemsItemIdMutationError = void

    /**
 * @summary Delete an item (Editor+). Tombstone.
 */
export const useDeleteListsListIdItemsItemId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteListsListIdItemsItemId>>, TError,{listId: string;itemId: string;params?: DeleteListsListIdItemsItemIdParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteListsListIdItemsItemId>>,
        TError,
        {listId: string;itemId: string;params?: DeleteListsListIdItemsItemIdParams},
        TContext
      > => {
      return useMutation(getDeleteListsListIdItemsItemIdMutationOptions(options), queryClient);
    }
    export const getPostListsListIdItemsItemIdCompleteUrl = (listId: string,
    itemId: string,) => {




  return `/lists/${listId}/items/${itemId}/complete`
}

/**
 * @summary Mark an item complete (Editor+).
 */
export const postListsListIdItemsItemIdComplete = async (listId: string,
    itemId: string,
    nullItemTimestampRequest?: null | ItemTimestampRequest, options?: RequestInit): Promise<ItemResponse> => {

  return customFetch<ItemResponse>(getPostListsListIdItemsItemIdCompleteUrl(listId,itemId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(nullItemTimestampRequest)
  }
);}




export const getPostListsListIdItemsItemIdCompleteMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postListsListIdItemsItemIdComplete>>, TError,{listId: string;itemId: string;data?: null | ItemTimestampRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postListsListIdItemsItemIdComplete>>, TError,{listId: string;itemId: string;data?: null | ItemTimestampRequest}, TContext> => {

const mutationKey = ['postListsListIdItemsItemIdComplete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postListsListIdItemsItemIdComplete>>, {listId: string;itemId: string;data?: null | ItemTimestampRequest}> = (props) => {
          const {listId,itemId,data} = props ?? {};

          return  postListsListIdItemsItemIdComplete(listId,itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostListsListIdItemsItemIdCompleteMutationResult = NonNullable<Awaited<ReturnType<typeof postListsListIdItemsItemIdComplete>>>
    export type PostListsListIdItemsItemIdCompleteMutationBody = null | ItemTimestampRequest | undefined
    export type PostListsListIdItemsItemIdCompleteMutationError = void

    /**
 * @summary Mark an item complete (Editor+).
 */
export const usePostListsListIdItemsItemIdComplete = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postListsListIdItemsItemIdComplete>>, TError,{listId: string;itemId: string;data?: null | ItemTimestampRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postListsListIdItemsItemIdComplete>>,
        TError,
        {listId: string;itemId: string;data?: null | ItemTimestampRequest},
        TContext
      > => {
      return useMutation(getPostListsListIdItemsItemIdCompleteMutationOptions(options), queryClient);
    }
    export const getPostListsListIdItemsItemIdReopenUrl = (listId: string,
    itemId: string,) => {




  return `/lists/${listId}/items/${itemId}/reopen`
}

/**
 * @summary Reopen a completed item (Editor+).
 */
export const postListsListIdItemsItemIdReopen = async (listId: string,
    itemId: string,
    nullItemTimestampRequest?: null | ItemTimestampRequest, options?: RequestInit): Promise<ItemResponse> => {

  return customFetch<ItemResponse>(getPostListsListIdItemsItemIdReopenUrl(listId,itemId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(nullItemTimestampRequest)
  }
);}




export const getPostListsListIdItemsItemIdReopenMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postListsListIdItemsItemIdReopen>>, TError,{listId: string;itemId: string;data?: null | ItemTimestampRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postListsListIdItemsItemIdReopen>>, TError,{listId: string;itemId: string;data?: null | ItemTimestampRequest}, TContext> => {

const mutationKey = ['postListsListIdItemsItemIdReopen'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postListsListIdItemsItemIdReopen>>, {listId: string;itemId: string;data?: null | ItemTimestampRequest}> = (props) => {
          const {listId,itemId,data} = props ?? {};

          return  postListsListIdItemsItemIdReopen(listId,itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostListsListIdItemsItemIdReopenMutationResult = NonNullable<Awaited<ReturnType<typeof postListsListIdItemsItemIdReopen>>>
    export type PostListsListIdItemsItemIdReopenMutationBody = null | ItemTimestampRequest | undefined
    export type PostListsListIdItemsItemIdReopenMutationError = void

    /**
 * @summary Reopen a completed item (Editor+).
 */
export const usePostListsListIdItemsItemIdReopen = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postListsListIdItemsItemIdReopen>>, TError,{listId: string;itemId: string;data?: null | ItemTimestampRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postListsListIdItemsItemIdReopen>>,
        TError,
        {listId: string;itemId: string;data?: null | ItemTimestampRequest},
        TContext
      > => {
      return useMutation(getPostListsListIdItemsItemIdReopenMutationOptions(options), queryClient);
    }
    export const getPostListsListIdItemsItemIdStatusUrl = (listId: string,
    itemId: string,) => {




  return `/lists/${listId}/items/${itemId}/status`
}

/**
 * Body `{ status (Open|InProgress|Blocked|Waiting|Done|Cancelled), reason?, occurredAt? }`. `Done` is equivalent to completing the item; `completed` is the derived `status == Done`.
 * @summary Set an item's lifecycle status (Editor+).
 */
export const postListsListIdItemsItemIdStatus = async (listId: string,
    itemId: string,
    setStatusRequest: SetStatusRequest, options?: RequestInit): Promise<ItemResponse> => {

  return customFetch<ItemResponse>(getPostListsListIdItemsItemIdStatusUrl(listId,itemId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(setStatusRequest)
  }
);}




export const getPostListsListIdItemsItemIdStatusMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postListsListIdItemsItemIdStatus>>, TError,{listId: string;itemId: string;data: SetStatusRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postListsListIdItemsItemIdStatus>>, TError,{listId: string;itemId: string;data: SetStatusRequest}, TContext> => {

const mutationKey = ['postListsListIdItemsItemIdStatus'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postListsListIdItemsItemIdStatus>>, {listId: string;itemId: string;data: SetStatusRequest}> = (props) => {
          const {listId,itemId,data} = props ?? {};

          return  postListsListIdItemsItemIdStatus(listId,itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostListsListIdItemsItemIdStatusMutationResult = NonNullable<Awaited<ReturnType<typeof postListsListIdItemsItemIdStatus>>>
    export type PostListsListIdItemsItemIdStatusMutationBody = SetStatusRequest
    export type PostListsListIdItemsItemIdStatusMutationError = ProblemDetails | void

    /**
 * @summary Set an item's lifecycle status (Editor+).
 */
export const usePostListsListIdItemsItemIdStatus = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postListsListIdItemsItemIdStatus>>, TError,{listId: string;itemId: string;data: SetStatusRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postListsListIdItemsItemIdStatus>>,
        TError,
        {listId: string;itemId: string;data: SetStatusRequest},
        TContext
      > => {
      return useMutation(getPostListsListIdItemsItemIdStatusMutationOptions(options), queryClient);
    }
    export const getPostListsListIdItemsItemIdMetadataUrl = (listId: string,
    itemId: string,) => {




  return `/lists/${listId}/items/${itemId}/metadata`
}

/**
 * Body `{ metadata (JSON object or null), occurredAt? }`. Server-side bookkeeping; never in VTODO or share links. Whole-field LWW.
 * @summary Set an item's free-form JSON metadata (Editor+).
 */
export const postListsListIdItemsItemIdMetadata = async (listId: string,
    itemId: string,
    setMetadataRequest: SetMetadataRequest, options?: RequestInit): Promise<ItemResponse> => {

  return customFetch<ItemResponse>(getPostListsListIdItemsItemIdMetadataUrl(listId,itemId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(setMetadataRequest)
  }
);}




export const getPostListsListIdItemsItemIdMetadataMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postListsListIdItemsItemIdMetadata>>, TError,{listId: string;itemId: string;data: SetMetadataRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postListsListIdItemsItemIdMetadata>>, TError,{listId: string;itemId: string;data: SetMetadataRequest}, TContext> => {

const mutationKey = ['postListsListIdItemsItemIdMetadata'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postListsListIdItemsItemIdMetadata>>, {listId: string;itemId: string;data: SetMetadataRequest}> = (props) => {
          const {listId,itemId,data} = props ?? {};

          return  postListsListIdItemsItemIdMetadata(listId,itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostListsListIdItemsItemIdMetadataMutationResult = NonNullable<Awaited<ReturnType<typeof postListsListIdItemsItemIdMetadata>>>
    export type PostListsListIdItemsItemIdMetadataMutationBody = SetMetadataRequest
    export type PostListsListIdItemsItemIdMetadataMutationError = ProblemDetails | void

    /**
 * @summary Set an item's free-form JSON metadata (Editor+).
 */
export const usePostListsListIdItemsItemIdMetadata = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postListsListIdItemsItemIdMetadata>>, TError,{listId: string;itemId: string;data: SetMetadataRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postListsListIdItemsItemIdMetadata>>,
        TError,
        {listId: string;itemId: string;data: SetMetadataRequest},
        TContext
      > => {
      return useMutation(getPostListsListIdItemsItemIdMetadataMutationOptions(options), queryClient);
    }
    export const getPostListsListIdItemsItemIdMoveUrl = (listId: string,
    itemId: string,) => {




  return `/lists/${listId}/items/${itemId}/move`
}

/**
 * Carries the fractional-index `sortOrder` string and optional `parentItemId`.
 * @summary Reparent / reorder an item (Editor+).
 */
export const postListsListIdItemsItemIdMove = async (listId: string,
    itemId: string,
    moveItemRequest: MoveItemRequest, options?: RequestInit): Promise<ItemResponse> => {

  return customFetch<ItemResponse>(getPostListsListIdItemsItemIdMoveUrl(listId,itemId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(moveItemRequest)
  }
);}




export const getPostListsListIdItemsItemIdMoveMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postListsListIdItemsItemIdMove>>, TError,{listId: string;itemId: string;data: MoveItemRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postListsListIdItemsItemIdMove>>, TError,{listId: string;itemId: string;data: MoveItemRequest}, TContext> => {

const mutationKey = ['postListsListIdItemsItemIdMove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postListsListIdItemsItemIdMove>>, {listId: string;itemId: string;data: MoveItemRequest}> = (props) => {
          const {listId,itemId,data} = props ?? {};

          return  postListsListIdItemsItemIdMove(listId,itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostListsListIdItemsItemIdMoveMutationResult = NonNullable<Awaited<ReturnType<typeof postListsListIdItemsItemIdMove>>>
    export type PostListsListIdItemsItemIdMoveMutationBody = MoveItemRequest
    export type PostListsListIdItemsItemIdMoveMutationError = ProblemDetails | void

    /**
 * @summary Reparent / reorder an item (Editor+).
 */
export const usePostListsListIdItemsItemIdMove = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postListsListIdItemsItemIdMove>>, TError,{listId: string;itemId: string;data: MoveItemRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postListsListIdItemsItemIdMove>>,
        TError,
        {listId: string;itemId: string;data: MoveItemRequest},
        TContext
      > => {
      return useMutation(getPostListsListIdItemsItemIdMoveMutationOptions(options), queryClient);
    }
