/**
 * Generated by orval 🍺
 * Do not edit manually.
 * LupiraTasks BFF
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateItemRequest,
  DeleteListItemParams,
  ItemDto,
  ItemTimestampRequest,
  ListListItemsParams,
  MoveItemRequest,
  ProblemDetails,
  UpdateItemRequest
} from '../models';

import { customFetch } from '../../fetcher';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getListListItemsUrl = (listId: string,
    params?: ListListItemsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/lists/${listId}/items?${stringifiedParams}` : `/api/lists/${listId}/items`
}

/**
 * Excludes deleted items; ordered by `sortOrder`. Filters: `completed`, `tagId`, `parentItemId`, `assignedTo`, `status`.
 * @summary List a list's items (Viewer+).
 */
export const listListItems = async (listId: string,
    params?: ListListItemsParams, options?: Parameters<typeof customFetch>[1]): Promise<ItemDto[]> => {

  return customFetch<ItemDto[]>(getListListItemsUrl(listId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListListItemsQueryKey = (listId: string,
    params?: ListListItemsParams,) => {
    return [
    `/api/lists/${listId}/items`, ...(params ? [params] : [])
    ] as const;
    }


export const getListListItemsQueryOptions = <TData = Awaited<ReturnType<typeof listListItems>>, TError = ProblemDetails>(listId: string,
    params?: ListListItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listListItems>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListListItemsQueryKey(listId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listListItems>>> = ({ signal }) => listListItems(listId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: listId !== null && listId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listListItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListListItemsQueryResult = NonNullable<Awaited<ReturnType<typeof listListItems>>>
export type ListListItemsQueryError = ProblemDetails


export function useListListItems<TData = Awaited<ReturnType<typeof listListItems>>, TError = ProblemDetails>(
 listId: string,
    params: undefined |  ListListItemsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listListItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listListItems>>,
          TError,
          Awaited<ReturnType<typeof listListItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListListItems<TData = Awaited<ReturnType<typeof listListItems>>, TError = ProblemDetails>(
 listId: string,
    params?: ListListItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listListItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listListItems>>,
          TError,
          Awaited<ReturnType<typeof listListItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListListItems<TData = Awaited<ReturnType<typeof listListItems>>, TError = ProblemDetails>(
 listId: string,
    params?: ListListItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listListItems>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List a list's items (Viewer+).
 */

export function useListListItems<TData = Awaited<ReturnType<typeof listListItems>>, TError = ProblemDetails>(
 listId: string,
    params?: ListListItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listListItems>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListListItemsQueryOptions(listId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getCreateListItemUrl = (listId: string,) => {




  return `/api/lists/${listId}/items`
}

/**
 * Body `{ id (GUIDv7), title, parentItemId?, dueAt?, assigneeEmail?, quantity?, unit?, priority? (0..9), tagIds?, sortOrder, occurredAt? }`. Re-sending an existing id is idempotent.
 * @summary Add an item (Editor+).
 */
export const createListItem = async (listId: string,
    createItemRequest: CreateItemRequest, options?: Parameters<typeof customFetch>[1]): Promise<ItemDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<ItemDto>(getCreateListItemUrl(listId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createItemRequest)
  }
);}





export const getCreateListItemMutationKey = () => ['createListItem'] as const;

export const getCreateListItemMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createListItem>>, TError,CreateListItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createListItem>>, TError,CreateListItemMutationVariables, TContext> => {

const mutationKey = getCreateListItemMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createListItem>>, CreateListItemMutationVariables> = (props) => {
          const {listId,data} = props ?? {};

          return  createListItem(listId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateListItemMutationResult = NonNullable<Awaited<ReturnType<typeof createListItem>>>
    export type CreateListItemMutationBody = CreateItemRequest
    export type CreateListItemMutationError = ProblemDetails
    export type CreateListItemMutationVariables = {listId: string;data: CreateItemRequest}

    /**
 * @summary Add an item (Editor+).
 */
export const useCreateListItem = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createListItem>>, TError,CreateListItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createListItem>>,
        TError,
        CreateListItemMutationVariables,
        TContext
      > => {
      return useMutation(getCreateListItemMutationOptions(options), queryClient);
    }
    export const getUpdateListItemUrl = (listId: string,
    itemId: string,) => {




  return `/api/lists/${listId}/items/${itemId}`
}

/**
 * One event per changed field. Use the `*Provided` flags so a null can mean 'clear' rather than 'unchanged' (e.g. `priority` 0..9 with `priorityProvided`). Tags via `addTagIds`/`removeTagIds`.
 * @summary Edit item fields (Editor+).
 */
export const updateListItem = async (listId: string,
    itemId: string,
    updateItemRequest: UpdateItemRequest, options?: Parameters<typeof customFetch>[1]): Promise<ItemDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<ItemDto>(getUpdateListItemUrl(listId,itemId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateItemRequest)
  }
);}





export const getUpdateListItemMutationKey = () => ['updateListItem'] as const;

export const getUpdateListItemMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateListItem>>, TError,UpdateListItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateListItem>>, TError,UpdateListItemMutationVariables, TContext> => {

const mutationKey = getUpdateListItemMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateListItem>>, UpdateListItemMutationVariables> = (props) => {
          const {listId,itemId,data} = props ?? {};

          return  updateListItem(listId,itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateListItemMutationResult = NonNullable<Awaited<ReturnType<typeof updateListItem>>>
    export type UpdateListItemMutationBody = UpdateItemRequest
    export type UpdateListItemMutationError = ProblemDetails
    export type UpdateListItemMutationVariables = {listId: string;itemId: string;data: UpdateItemRequest}

    /**
 * @summary Edit item fields (Editor+).
 */
export const useUpdateListItem = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateListItem>>, TError,UpdateListItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateListItem>>,
        TError,
        UpdateListItemMutationVariables,
        TContext
      > => {
      return useMutation(getUpdateListItemMutationOptions(options), queryClient);
    }
    export const getDeleteListItemUrl = (listId: string,
    itemId: string,
    params?: DeleteListItemParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/lists/${listId}/items/${itemId}?${stringifiedParams}` : `/api/lists/${listId}/items/${itemId}`
}

/**
 * Optional `?occurredAt=` (ISO-8601) carries the client timestamp for LWW.
 * @summary Delete an item (Editor+). Tombstone.
 */
export const deleteListItem = async (listId: string,
    itemId: string,
    params?: DeleteListItemParams, options?: Parameters<typeof customFetch>[1]): Promise<void> => {

  return customFetch<void>(getDeleteListItemUrl(listId,itemId,params),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteListItemMutationKey = () => ['deleteListItem'] as const;

export const getDeleteListItemMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteListItem>>, TError,DeleteListItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteListItem>>, TError,DeleteListItemMutationVariables, TContext> => {

const mutationKey = getDeleteListItemMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteListItem>>, DeleteListItemMutationVariables> = (props) => {
          const {listId,itemId,params} = props ?? {};

          return  deleteListItem(listId,itemId,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteListItemMutationResult = NonNullable<Awaited<ReturnType<typeof deleteListItem>>>

    export type DeleteListItemMutationError = ProblemDetails
    export type DeleteListItemMutationVariables = {listId: string;itemId: string;params?: DeleteListItemParams}

    /**
 * @summary Delete an item (Editor+). Tombstone.
 */
export const useDeleteListItem = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteListItem>>, TError,DeleteListItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteListItem>>,
        TError,
        DeleteListItemMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteListItemMutationOptions(options), queryClient);
    }
    export const getCompleteItemUrl = (listId: string,
    itemId: string,) => {




  return `/api/lists/${listId}/items/${itemId}/complete`
}

/**
 * @summary Mark an item complete (Editor+).
 */
export const completeItem = async (listId: string,
    itemId: string,
    nullItemTimestampRequest?: null | ItemTimestampRequest, options?: Parameters<typeof customFetch>[1]): Promise<ItemDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<ItemDto>(getCompleteItemUrl(listId,itemId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(nullItemTimestampRequest)
  }
);}





export const getCompleteItemMutationKey = () => ['completeItem'] as const;

export const getCompleteItemMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeItem>>, TError,CompleteItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof completeItem>>, TError,CompleteItemMutationVariables, TContext> => {

const mutationKey = getCompleteItemMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof completeItem>>, CompleteItemMutationVariables> = (props) => {
          const {listId,itemId,data} = props ?? {};

          return  completeItem(listId,itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CompleteItemMutationResult = NonNullable<Awaited<ReturnType<typeof completeItem>>>
    export type CompleteItemMutationBody = null | ItemTimestampRequest | undefined
    export type CompleteItemMutationError = ProblemDetails
    export type CompleteItemMutationVariables = {listId: string;itemId: string;data?: null | ItemTimestampRequest}

    /**
 * @summary Mark an item complete (Editor+).
 */
export const useCompleteItem = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeItem>>, TError,CompleteItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof completeItem>>,
        TError,
        CompleteItemMutationVariables,
        TContext
      > => {
      return useMutation(getCompleteItemMutationOptions(options), queryClient);
    }
    export const getMoveItemUrl = (listId: string,
    itemId: string,) => {




  return `/api/lists/${listId}/items/${itemId}/move`
}

/**
 * Carries the fractional-index `sortOrder` string and optional `parentItemId`.
 * @summary Reparent / reorder an item (Editor+).
 */
export const moveItem = async (listId: string,
    itemId: string,
    moveItemRequest: MoveItemRequest, options?: Parameters<typeof customFetch>[1]): Promise<ItemDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<ItemDto>(getMoveItemUrl(listId,itemId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(moveItemRequest)
  }
);}





export const getMoveItemMutationKey = () => ['moveItem'] as const;

export const getMoveItemMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof moveItem>>, TError,MoveItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof moveItem>>, TError,MoveItemMutationVariables, TContext> => {

const mutationKey = getMoveItemMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof moveItem>>, MoveItemMutationVariables> = (props) => {
          const {listId,itemId,data} = props ?? {};

          return  moveItem(listId,itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MoveItemMutationResult = NonNullable<Awaited<ReturnType<typeof moveItem>>>
    export type MoveItemMutationBody = MoveItemRequest
    export type MoveItemMutationError = ProblemDetails
    export type MoveItemMutationVariables = {listId: string;itemId: string;data: MoveItemRequest}

    /**
 * @summary Reparent / reorder an item (Editor+).
 */
export const useMoveItem = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof moveItem>>, TError,MoveItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof moveItem>>,
        TError,
        MoveItemMutationVariables,
        TContext
      > => {
      return useMutation(getMoveItemMutationOptions(options), queryClient);
    }
    export const getReopenItemUrl = (listId: string,
    itemId: string,) => {




  return `/api/lists/${listId}/items/${itemId}/reopen`
}

/**
 * @summary Reopen a completed item (Editor+).
 */
export const reopenItem = async (listId: string,
    itemId: string,
    nullItemTimestampRequest?: null | ItemTimestampRequest, options?: Parameters<typeof customFetch>[1]): Promise<ItemDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<ItemDto>(getReopenItemUrl(listId,itemId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(nullItemTimestampRequest)
  }
);}





export const getReopenItemMutationKey = () => ['reopenItem'] as const;

export const getReopenItemMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reopenItem>>, TError,ReopenItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof reopenItem>>, TError,ReopenItemMutationVariables, TContext> => {

const mutationKey = getReopenItemMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reopenItem>>, ReopenItemMutationVariables> = (props) => {
          const {listId,itemId,data} = props ?? {};

          return  reopenItem(listId,itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ReopenItemMutationResult = NonNullable<Awaited<ReturnType<typeof reopenItem>>>
    export type ReopenItemMutationBody = null | ItemTimestampRequest | undefined
    export type ReopenItemMutationError = ProblemDetails
    export type ReopenItemMutationVariables = {listId: string;itemId: string;data?: null | ItemTimestampRequest}

    /**
 * @summary Reopen a completed item (Editor+).
 */
export const useReopenItem = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reopenItem>>, TError,ReopenItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reopenItem>>,
        TError,
        ReopenItemMutationVariables,
        TContext
      > => {
      return useMutation(getReopenItemMutationOptions(options), queryClient);
    }
