/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Tasks API
 * Task and command processing backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateItemRequest,
  DeleteListItemParams,
  ItemDto,
  ItemTimestampRequest,
  ListItemsParams,
  ListListItemsParams,
  MoveItemRequest,
  ProblemDetails,
  SetMetadataRequest,
  SetStatusRequest,
  UpdateItemRequest
} from '../models';

import { customFetch } from '../../fetcher';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getListItemsUrl = (params?: ListItemsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/items?${stringifiedParams}` : `/items`
}

/**
 * Case-insensitive `query` title substring, optional `completed`/`status`. `dueFrom`/`dueTo` bound `dueAt` half-open `[from, to)`; either bound implies `dueAt` is set. Spans every list the caller is a member of (archived included).
 * @summary Search items across the caller's lists (Viewer+).
 */
export const listItems = async (params?: ListItemsParams, options?: Parameters<typeof customFetch>[1]): Promise<ItemDto[]> => {

  return customFetch<ItemDto[]>(getListItemsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListItemsQueryKey = (params?: ListItemsParams,) => {
    return [
    `/items`, ...(params ? [params] : [])
    ] as const;
    }


export const getListItemsQueryOptions = <TData = Awaited<ReturnType<typeof listItems>>, TError = ProblemDetails>(params?: ListItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listItems>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListItemsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listItems>>> = ({ signal }) => listItems(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListItemsQueryResult = NonNullable<Awaited<ReturnType<typeof listItems>>>
export type ListItemsQueryError = ProblemDetails


export function useListItems<TData = Awaited<ReturnType<typeof listItems>>, TError = ProblemDetails>(
 params: undefined |  ListItemsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listItems>>,
          TError,
          Awaited<ReturnType<typeof listItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListItems<TData = Awaited<ReturnType<typeof listItems>>, TError = ProblemDetails>(
 params?: ListItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listItems>>,
          TError,
          Awaited<ReturnType<typeof listItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListItems<TData = Awaited<ReturnType<typeof listItems>>, TError = ProblemDetails>(
 params?: ListItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listItems>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search items across the caller's lists (Viewer+).
 */

export function useListItems<TData = Awaited<ReturnType<typeof listItems>>, TError = ProblemDetails>(
 params?: ListItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listItems>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListItemsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getUpdateItemUrl = (itemId: string,) => {




  return `/items/${itemId}`
}

/**
 * Same body as the list-scoped PATCH (`*Provided` flags). 404 if no such item or the caller can't edit its list.
 * @summary Edit item fields addressed by id (Editor+); the list is resolved server-side.
 */
export const updateItem = async (itemId: string,
    updateItemRequest: UpdateItemRequest, options?: Parameters<typeof customFetch>[1]): Promise<ItemDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<ItemDto>(getUpdateItemUrl(itemId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateItemRequest)
  }
);}





export const getUpdateItemMutationKey = () => ['updateItem'] as const;

export const getUpdateItemMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateItem>>, TError,UpdateItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateItem>>, TError,UpdateItemMutationVariables, TContext> => {

const mutationKey = getUpdateItemMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateItem>>, UpdateItemMutationVariables> = (props) => {
          const {itemId,data} = props ?? {};

          return  updateItem(itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateItemMutationResult = NonNullable<Awaited<ReturnType<typeof updateItem>>>
    export type UpdateItemMutationBody = UpdateItemRequest
    export type UpdateItemMutationError = ProblemDetails
    export type UpdateItemMutationVariables = {itemId: string;data: UpdateItemRequest}

    /**
 * @summary Edit item fields addressed by id (Editor+); the list is resolved server-side.
 */
export const useUpdateItem = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateItem>>, TError,UpdateItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateItem>>,
        TError,
        UpdateItemMutationVariables,
        TContext
      > => {
      return useMutation(getUpdateItemMutationOptions(options), queryClient);
    }
    export const getSetItemMetadataUrl = (itemId: string,) => {




  return `/items/${itemId}/metadata`
}

/**
 * Body `{ metadata (JSON object or null), occurredAt? }`. Whole-field LWW. 404 if no such item or the caller can't edit its list.
 * @summary Set an item's metadata addressed by id (Editor+); the list is resolved server-side.
 */
export const setItemMetadata = async (itemId: string,
    setMetadataRequest: SetMetadataRequest, options?: Parameters<typeof customFetch>[1]): Promise<ItemDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<ItemDto>(getSetItemMetadataUrl(itemId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(setMetadataRequest)
  }
);}





export const getSetItemMetadataMutationKey = () => ['setItemMetadata'] as const;

export const getSetItemMetadataMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setItemMetadata>>, TError,SetItemMetadataMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof setItemMetadata>>, TError,SetItemMetadataMutationVariables, TContext> => {

const mutationKey = getSetItemMetadataMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setItemMetadata>>, SetItemMetadataMutationVariables> = (props) => {
          const {itemId,data} = props ?? {};

          return  setItemMetadata(itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SetItemMetadataMutationResult = NonNullable<Awaited<ReturnType<typeof setItemMetadata>>>
    export type SetItemMetadataMutationBody = SetMetadataRequest
    export type SetItemMetadataMutationError = ProblemDetails
    export type SetItemMetadataMutationVariables = {itemId: string;data: SetMetadataRequest}

    /**
 * @summary Set an item's metadata addressed by id (Editor+); the list is resolved server-side.
 */
export const useSetItemMetadata = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setItemMetadata>>, TError,SetItemMetadataMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof setItemMetadata>>,
        TError,
        SetItemMetadataMutationVariables,
        TContext
      > => {
      return useMutation(getSetItemMetadataMutationOptions(options), queryClient);
    }
    export const getListListItemsUrl = (listId: string,
    params?: ListListItemsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/lists/${listId}/items?${stringifiedParams}` : `/lists/${listId}/items`
}

/**
 * Excludes deleted items; ordered by `sortOrder`. Filters: `completed`, `tagId`, `parentItemId`, `assignedTo`, `status`.
 * @summary List a list's items (Viewer+).
 */
export const listListItems = async (listId: string,
    params?: ListListItemsParams, options?: Parameters<typeof customFetch>[1]): Promise<ItemDto[]> => {

  return customFetch<ItemDto[]>(getListListItemsUrl(listId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListListItemsQueryKey = (listId: string,
    params?: ListListItemsParams,) => {
    return [
    `/lists/${listId}/items`, ...(params ? [params] : [])
    ] as const;
    }


export const getListListItemsQueryOptions = <TData = Awaited<ReturnType<typeof listListItems>>, TError = ProblemDetails>(listId: string,
    params?: ListListItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listListItems>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListListItemsQueryKey(listId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listListItems>>> = ({ signal }) => listListItems(listId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: listId !== null && listId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listListItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListListItemsQueryResult = NonNullable<Awaited<ReturnType<typeof listListItems>>>
export type ListListItemsQueryError = ProblemDetails


export function useListListItems<TData = Awaited<ReturnType<typeof listListItems>>, TError = ProblemDetails>(
 listId: string,
    params: undefined |  ListListItemsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listListItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listListItems>>,
          TError,
          Awaited<ReturnType<typeof listListItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListListItems<TData = Awaited<ReturnType<typeof listListItems>>, TError = ProblemDetails>(
 listId: string,
    params?: ListListItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listListItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listListItems>>,
          TError,
          Awaited<ReturnType<typeof listListItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListListItems<TData = Awaited<ReturnType<typeof listListItems>>, TError = ProblemDetails>(
 listId: string,
    params?: ListListItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listListItems>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List a list's items (Viewer+).
 */

export function useListListItems<TData = Awaited<ReturnType<typeof listListItems>>, TError = ProblemDetails>(
 listId: string,
    params?: ListListItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listListItems>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListListItemsQueryOptions(listId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getCreateListItemUrl = (listId: string,) => {




  return `/lists/${listId}/items`
}

/**
 * Body `{ id (GUIDv7), title, parentItemId?, dueAt?, assigneeEmail?, quantity?, unit?, priority? (0..9), tagIds?, sortOrder, occurredAt? }`. Re-sending an existing id is idempotent.
 * @summary Add an item (Editor+).
 */
export const createListItem = async (listId: string,
    createItemRequest: CreateItemRequest, options?: Parameters<typeof customFetch>[1]): Promise<ItemDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<ItemDto>(getCreateListItemUrl(listId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createItemRequest)
  }
);}





export const getCreateListItemMutationKey = () => ['createListItem'] as const;

export const getCreateListItemMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createListItem>>, TError,CreateListItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createListItem>>, TError,CreateListItemMutationVariables, TContext> => {

const mutationKey = getCreateListItemMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createListItem>>, CreateListItemMutationVariables> = (props) => {
          const {listId,data} = props ?? {};

          return  createListItem(listId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateListItemMutationResult = NonNullable<Awaited<ReturnType<typeof createListItem>>>
    export type CreateListItemMutationBody = CreateItemRequest
    export type CreateListItemMutationError = ProblemDetails
    export type CreateListItemMutationVariables = {listId: string;data: CreateItemRequest}

    /**
 * @summary Add an item (Editor+).
 */
export const useCreateListItem = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createListItem>>, TError,CreateListItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createListItem>>,
        TError,
        CreateListItemMutationVariables,
        TContext
      > => {
      return useMutation(getCreateListItemMutationOptions(options), queryClient);
    }
    export const getGetItemUrl = (listId: string,
    itemId: string,) => {




  return `/lists/${listId}/items/${itemId}`
}

/**
 * @summary Get a single item (Viewer+).
 */
export const getItem = async (listId: string,
    itemId: string, options?: Parameters<typeof customFetch>[1]): Promise<ItemDto> => {

  return customFetch<ItemDto>(getGetItemUrl(listId,itemId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetItemQueryKey = (listId: string,
    itemId: string,) => {
    return [
    `/lists/${listId}/items/${itemId}`
    ] as const;
    }


export const getGetItemQueryOptions = <TData = Awaited<ReturnType<typeof getItem>>, TError = ProblemDetails>(listId: string,
    itemId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetItemQueryKey(listId,itemId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getItem>>> = ({ signal }) => getItem(listId,itemId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: listId !== null && listId !== undefined && itemId !== null && itemId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetItemQueryResult = NonNullable<Awaited<ReturnType<typeof getItem>>>
export type GetItemQueryError = ProblemDetails


export function useGetItem<TData = Awaited<ReturnType<typeof getItem>>, TError = ProblemDetails>(
 listId: string,
    itemId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItem>>,
          TError,
          Awaited<ReturnType<typeof getItem>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItem<TData = Awaited<ReturnType<typeof getItem>>, TError = ProblemDetails>(
 listId: string,
    itemId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItem>>,
          TError,
          Awaited<ReturnType<typeof getItem>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItem<TData = Awaited<ReturnType<typeof getItem>>, TError = ProblemDetails>(
 listId: string,
    itemId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a single item (Viewer+).
 */

export function useGetItem<TData = Awaited<ReturnType<typeof getItem>>, TError = ProblemDetails>(
 listId: string,
    itemId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetItemQueryOptions(listId,itemId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getUpdateListItemUrl = (listId: string,
    itemId: string,) => {




  return `/lists/${listId}/items/${itemId}`
}

/**
 * One event per changed field. Use the `*Provided` flags so a null can mean 'clear' rather than 'unchanged' (e.g. `priority` 0..9 with `priorityProvided`). Tags via `addTagIds`/`removeTagIds`.
 * @summary Edit item fields (Editor+).
 */
export const updateListItem = async (listId: string,
    itemId: string,
    updateItemRequest: UpdateItemRequest, options?: Parameters<typeof customFetch>[1]): Promise<ItemDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<ItemDto>(getUpdateListItemUrl(listId,itemId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateItemRequest)
  }
);}





export const getUpdateListItemMutationKey = () => ['updateListItem'] as const;

export const getUpdateListItemMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateListItem>>, TError,UpdateListItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateListItem>>, TError,UpdateListItemMutationVariables, TContext> => {

const mutationKey = getUpdateListItemMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateListItem>>, UpdateListItemMutationVariables> = (props) => {
          const {listId,itemId,data} = props ?? {};

          return  updateListItem(listId,itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateListItemMutationResult = NonNullable<Awaited<ReturnType<typeof updateListItem>>>
    export type UpdateListItemMutationBody = UpdateItemRequest
    export type UpdateListItemMutationError = ProblemDetails
    export type UpdateListItemMutationVariables = {listId: string;itemId: string;data: UpdateItemRequest}

    /**
 * @summary Edit item fields (Editor+).
 */
export const useUpdateListItem = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateListItem>>, TError,UpdateListItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateListItem>>,
        TError,
        UpdateListItemMutationVariables,
        TContext
      > => {
      return useMutation(getUpdateListItemMutationOptions(options), queryClient);
    }
    export const getDeleteListItemUrl = (listId: string,
    itemId: string,
    params?: DeleteListItemParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/lists/${listId}/items/${itemId}?${stringifiedParams}` : `/lists/${listId}/items/${itemId}`
}

/**
 * Optional `?occurredAt=` (ISO-8601) carries the client timestamp for LWW.
 * @summary Delete an item (Editor+). Tombstone.
 */
export const deleteListItem = async (listId: string,
    itemId: string,
    params?: DeleteListItemParams, options?: Parameters<typeof customFetch>[1]): Promise<void> => {

  return customFetch<void>(getDeleteListItemUrl(listId,itemId,params),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteListItemMutationKey = () => ['deleteListItem'] as const;

export const getDeleteListItemMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteListItem>>, TError,DeleteListItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteListItem>>, TError,DeleteListItemMutationVariables, TContext> => {

const mutationKey = getDeleteListItemMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteListItem>>, DeleteListItemMutationVariables> = (props) => {
          const {listId,itemId,params} = props ?? {};

          return  deleteListItem(listId,itemId,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteListItemMutationResult = NonNullable<Awaited<ReturnType<typeof deleteListItem>>>

    export type DeleteListItemMutationError = ProblemDetails
    export type DeleteListItemMutationVariables = {listId: string;itemId: string;params?: DeleteListItemParams}

    /**
 * @summary Delete an item (Editor+). Tombstone.
 */
export const useDeleteListItem = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteListItem>>, TError,DeleteListItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteListItem>>,
        TError,
        DeleteListItemMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteListItemMutationOptions(options), queryClient);
    }
    export const getCompleteItemUrl = (listId: string,
    itemId: string,) => {




  return `/lists/${listId}/items/${itemId}/complete`
}

/**
 * @summary Mark an item complete (Editor+).
 */
export const completeItem = async (listId: string,
    itemId: string,
    nullItemTimestampRequest?: null | ItemTimestampRequest, options?: Parameters<typeof customFetch>[1]): Promise<ItemDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<ItemDto>(getCompleteItemUrl(listId,itemId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(nullItemTimestampRequest)
  }
);}





export const getCompleteItemMutationKey = () => ['completeItem'] as const;

export const getCompleteItemMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeItem>>, TError,CompleteItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof completeItem>>, TError,CompleteItemMutationVariables, TContext> => {

const mutationKey = getCompleteItemMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof completeItem>>, CompleteItemMutationVariables> = (props) => {
          const {listId,itemId,data} = props ?? {};

          return  completeItem(listId,itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CompleteItemMutationResult = NonNullable<Awaited<ReturnType<typeof completeItem>>>
    export type CompleteItemMutationBody = null | ItemTimestampRequest | undefined
    export type CompleteItemMutationError = ProblemDetails
    export type CompleteItemMutationVariables = {listId: string;itemId: string;data?: null | ItemTimestampRequest}

    /**
 * @summary Mark an item complete (Editor+).
 */
export const useCompleteItem = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeItem>>, TError,CompleteItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof completeItem>>,
        TError,
        CompleteItemMutationVariables,
        TContext
      > => {
      return useMutation(getCompleteItemMutationOptions(options), queryClient);
    }
    export const getReopenItemUrl = (listId: string,
    itemId: string,) => {




  return `/lists/${listId}/items/${itemId}/reopen`
}

/**
 * @summary Reopen a completed item (Editor+).
 */
export const reopenItem = async (listId: string,
    itemId: string,
    nullItemTimestampRequest?: null | ItemTimestampRequest, options?: Parameters<typeof customFetch>[1]): Promise<ItemDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<ItemDto>(getReopenItemUrl(listId,itemId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(nullItemTimestampRequest)
  }
);}





export const getReopenItemMutationKey = () => ['reopenItem'] as const;

export const getReopenItemMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reopenItem>>, TError,ReopenItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof reopenItem>>, TError,ReopenItemMutationVariables, TContext> => {

const mutationKey = getReopenItemMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reopenItem>>, ReopenItemMutationVariables> = (props) => {
          const {listId,itemId,data} = props ?? {};

          return  reopenItem(listId,itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ReopenItemMutationResult = NonNullable<Awaited<ReturnType<typeof reopenItem>>>
    export type ReopenItemMutationBody = null | ItemTimestampRequest | undefined
    export type ReopenItemMutationError = ProblemDetails
    export type ReopenItemMutationVariables = {listId: string;itemId: string;data?: null | ItemTimestampRequest}

    /**
 * @summary Reopen a completed item (Editor+).
 */
export const useReopenItem = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reopenItem>>, TError,ReopenItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reopenItem>>,
        TError,
        ReopenItemMutationVariables,
        TContext
      > => {
      return useMutation(getReopenItemMutationOptions(options), queryClient);
    }
    export const getSetItemStatusUrl = (listId: string,
    itemId: string,) => {




  return `/lists/${listId}/items/${itemId}/status`
}

/**
 * Body `{ status (Open|InProgress|Blocked|Waiting|Done|Cancelled), reason?, occurredAt? }`. `Done` is equivalent to completing the item; `completed` is the derived `status == Done`.
 * @summary Set an item's lifecycle status (Editor+).
 */
export const setItemStatus = async (listId: string,
    itemId: string,
    setStatusRequest: SetStatusRequest, options?: Parameters<typeof customFetch>[1]): Promise<ItemDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<ItemDto>(getSetItemStatusUrl(listId,itemId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(setStatusRequest)
  }
);}





export const getSetItemStatusMutationKey = () => ['setItemStatus'] as const;

export const getSetItemStatusMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setItemStatus>>, TError,SetItemStatusMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof setItemStatus>>, TError,SetItemStatusMutationVariables, TContext> => {

const mutationKey = getSetItemStatusMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setItemStatus>>, SetItemStatusMutationVariables> = (props) => {
          const {listId,itemId,data} = props ?? {};

          return  setItemStatus(listId,itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SetItemStatusMutationResult = NonNullable<Awaited<ReturnType<typeof setItemStatus>>>
    export type SetItemStatusMutationBody = SetStatusRequest
    export type SetItemStatusMutationError = ProblemDetails
    export type SetItemStatusMutationVariables = {listId: string;itemId: string;data: SetStatusRequest}

    /**
 * @summary Set an item's lifecycle status (Editor+).
 */
export const useSetItemStatus = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setItemStatus>>, TError,SetItemStatusMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof setItemStatus>>,
        TError,
        SetItemStatusMutationVariables,
        TContext
      > => {
      return useMutation(getSetItemStatusMutationOptions(options), queryClient);
    }
    export const getSetListItemMetadataUrl = (listId: string,
    itemId: string,) => {




  return `/lists/${listId}/items/${itemId}/metadata`
}

/**
 * Body `{ metadata (JSON object or null), occurredAt? }`. Server-side bookkeeping; never in VTODO or share links. Whole-field LWW.
 * @summary Set an item's free-form JSON metadata (Editor+).
 */
export const setListItemMetadata = async (listId: string,
    itemId: string,
    setMetadataRequest: SetMetadataRequest, options?: Parameters<typeof customFetch>[1]): Promise<ItemDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<ItemDto>(getSetListItemMetadataUrl(listId,itemId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(setMetadataRequest)
  }
);}





export const getSetListItemMetadataMutationKey = () => ['setListItemMetadata'] as const;

export const getSetListItemMetadataMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setListItemMetadata>>, TError,SetListItemMetadataMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof setListItemMetadata>>, TError,SetListItemMetadataMutationVariables, TContext> => {

const mutationKey = getSetListItemMetadataMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setListItemMetadata>>, SetListItemMetadataMutationVariables> = (props) => {
          const {listId,itemId,data} = props ?? {};

          return  setListItemMetadata(listId,itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SetListItemMetadataMutationResult = NonNullable<Awaited<ReturnType<typeof setListItemMetadata>>>
    export type SetListItemMetadataMutationBody = SetMetadataRequest
    export type SetListItemMetadataMutationError = ProblemDetails
    export type SetListItemMetadataMutationVariables = {listId: string;itemId: string;data: SetMetadataRequest}

    /**
 * @summary Set an item's free-form JSON metadata (Editor+).
 */
export const useSetListItemMetadata = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setListItemMetadata>>, TError,SetListItemMetadataMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof setListItemMetadata>>,
        TError,
        SetListItemMetadataMutationVariables,
        TContext
      > => {
      return useMutation(getSetListItemMetadataMutationOptions(options), queryClient);
    }
    export const getMoveItemUrl = (listId: string,
    itemId: string,) => {




  return `/lists/${listId}/items/${itemId}/move`
}

/**
 * Carries the fractional-index `sortOrder` string and optional `parentItemId`.
 * @summary Reparent / reorder an item (Editor+).
 */
export const moveItem = async (listId: string,
    itemId: string,
    moveItemRequest: MoveItemRequest, options?: Parameters<typeof customFetch>[1]): Promise<ItemDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<ItemDto>(getMoveItemUrl(listId,itemId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(moveItemRequest)
  }
);}





export const getMoveItemMutationKey = () => ['moveItem'] as const;

export const getMoveItemMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof moveItem>>, TError,MoveItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof moveItem>>, TError,MoveItemMutationVariables, TContext> => {

const mutationKey = getMoveItemMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof moveItem>>, MoveItemMutationVariables> = (props) => {
          const {listId,itemId,data} = props ?? {};

          return  moveItem(listId,itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MoveItemMutationResult = NonNullable<Awaited<ReturnType<typeof moveItem>>>
    export type MoveItemMutationBody = MoveItemRequest
    export type MoveItemMutationError = ProblemDetails
    export type MoveItemMutationVariables = {listId: string;itemId: string;data: MoveItemRequest}

    /**
 * @summary Reparent / reorder an item (Editor+).
 */
export const useMoveItem = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof moveItem>>, TError,MoveItemMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof moveItem>>,
        TError,
        MoveItemMutationVariables,
        TContext
      > => {
      return useMutation(getMoveItemMutationOptions(options), queryClient);
    }
