/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Lupira Tasks API
 * Task and command processing backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddMemberRequest,
  CreateListRequest,
  ListCollectionResponse,
  ListListsParams,
  ListResponse,
  ProblemDetails,
  SetListOrderRequest,
  UpdateListRequest,
  UpdateMemberRoleRequest
} from '../models';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getListListsUrl = (params?: ListListsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/lists?${stringifiedParams}` : `/lists`
}

/**
 * `?archived=true` returns the caller's archived lists instead of the active ones.
 * @summary List the lists the caller is a member of.
 */
export const listLists = async (params?: ListListsParams, options?: RequestInit): Promise<ListCollectionResponse> => {

  return customFetch<ListCollectionResponse>(getListListsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListListsQueryKey = (params?: ListListsParams,) => {
    return [
    `/lists`, ...(params ? [params] : [])
    ] as const;
    }


export const getListListsQueryOptions = <TData = Awaited<ReturnType<typeof listLists>>, TError = ProblemDetails>(params?: ListListsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLists>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListListsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listLists>>> = ({ signal }) => listLists(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listLists>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListListsQueryResult = NonNullable<Awaited<ReturnType<typeof listLists>>>
export type ListListsQueryError = ProblemDetails


export function useListLists<TData = Awaited<ReturnType<typeof listLists>>, TError = ProblemDetails>(
 params: undefined |  ListListsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLists>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listLists>>,
          TError,
          Awaited<ReturnType<typeof listLists>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListLists<TData = Awaited<ReturnType<typeof listLists>>, TError = ProblemDetails>(
 params?: ListListsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLists>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listLists>>,
          TError,
          Awaited<ReturnType<typeof listLists>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListLists<TData = Awaited<ReturnType<typeof listLists>>, TError = ProblemDetails>(
 params?: ListListsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLists>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List the lists the caller is a member of.
 */

export function useListLists<TData = Awaited<ReturnType<typeof listLists>>, TError = ProblemDetails>(
 params?: ListListsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLists>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListListsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getCreateListUrl = () => {




  return `/lists`
}

/**
 * Body `{ id (GUIDv7), name, kind, color? }`. `kind` is `Todo`, `Shopping`, or `Agent` (agent/system-owned lists). Re-sending an existing id is an idempotent success.
 * @summary Create a list; the caller becomes Owner.
 */
export const createList = async (createListRequest: CreateListRequest, options?: RequestInit): Promise<ListResponse> => {

  return customFetch<ListResponse>(getCreateListUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createListRequest)
  }
);}




export const getCreateListMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createList>>, TError,{data: CreateListRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createList>>, TError,{data: CreateListRequest}, TContext> => {

const mutationKey = ['createList'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createList>>, {data: CreateListRequest}> = (props) => {
          const {data} = props ?? {};

          return  createList(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateListMutationResult = NonNullable<Awaited<ReturnType<typeof createList>>>
    export type CreateListMutationBody = CreateListRequest
    export type CreateListMutationError = ProblemDetails

    /**
 * @summary Create a list; the caller becomes Owner.
 */
export const useCreateList = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createList>>, TError,{data: CreateListRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createList>>,
        TError,
        {data: CreateListRequest},
        TContext
      > => {
      return useMutation(getCreateListMutationOptions(options), queryClient);
    }
    export const getGetListUrl = (listId: string,) => {




  return `/lists/${listId}`
}

/**
 * @summary Get a list with its members and tags (Viewer+).
 */
export const getList = async (listId: string, options?: RequestInit): Promise<ListResponse> => {

  return customFetch<ListResponse>(getGetListUrl(listId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetListQueryKey = (listId: string,) => {
    return [
    `/lists/${listId}`
    ] as const;
    }


export const getGetListQueryOptions = <TData = Awaited<ReturnType<typeof getList>>, TError = ProblemDetails>(listId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetListQueryKey(listId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getList>>> = ({ signal }) => getList(listId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: listId !== null && listId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetListQueryResult = NonNullable<Awaited<ReturnType<typeof getList>>>
export type GetListQueryError = ProblemDetails


export function useGetList<TData = Awaited<ReturnType<typeof getList>>, TError = ProblemDetails>(
 listId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getList>>,
          TError,
          Awaited<ReturnType<typeof getList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetList<TData = Awaited<ReturnType<typeof getList>>, TError = ProblemDetails>(
 listId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getList>>,
          TError,
          Awaited<ReturnType<typeof getList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetList<TData = Awaited<ReturnType<typeof getList>>, TError = ProblemDetails>(
 listId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a list with its members and tags (Viewer+).
 */

export function useGetList<TData = Awaited<ReturnType<typeof getList>>, TError = ProblemDetails>(
 listId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetListQueryOptions(listId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getUpdateListUrl = (listId: string,) => {




  return `/lists/${listId}`
}

/**
 * Each provided field emits its own event. Set `colorProvided` to apply `color` (incl. clearing it). Send `simplePriority` (bool) to switch between simple on/off and the full 0..9 scale.
 * @summary Rename / recolor a list, or set its priority mode (Editor+).
 */
export const updateList = async (listId: string,
    updateListRequest: UpdateListRequest, options?: RequestInit): Promise<ListResponse> => {

  return customFetch<ListResponse>(getUpdateListUrl(listId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateListRequest)
  }
);}




export const getUpdateListMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateList>>, TError,{listId: string;data: UpdateListRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateList>>, TError,{listId: string;data: UpdateListRequest}, TContext> => {

const mutationKey = ['updateList'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateList>>, {listId: string;data: UpdateListRequest}> = (props) => {
          const {listId,data} = props ?? {};

          return  updateList(listId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateListMutationResult = NonNullable<Awaited<ReturnType<typeof updateList>>>
    export type UpdateListMutationBody = UpdateListRequest
    export type UpdateListMutationError = ProblemDetails

    /**
 * @summary Rename / recolor a list, or set its priority mode (Editor+).
 */
export const useUpdateList = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateList>>, TError,{listId: string;data: UpdateListRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateList>>,
        TError,
        {listId: string;data: UpdateListRequest},
        TContext
      > => {
      return useMutation(getUpdateListMutationOptions(options), queryClient);
    }
    export const getDeleteListUrl = (listId: string,) => {




  return `/lists/${listId}`
}

/**
 * @summary Delete a list (Owner). Tombstone — stream retained.
 */
export const deleteList = async (listId: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getDeleteListUrl(listId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteListMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteList>>, TError,{listId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteList>>, TError,{listId: string}, TContext> => {

const mutationKey = ['deleteList'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteList>>, {listId: string}> = (props) => {
          const {listId} = props ?? {};

          return  deleteList(listId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteListMutationResult = NonNullable<Awaited<ReturnType<typeof deleteList>>>

    export type DeleteListMutationError = ProblemDetails

    /**
 * @summary Delete a list (Owner). Tombstone — stream retained.
 */
export const useDeleteList = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteList>>, TError,{listId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteList>>,
        TError,
        {listId: string},
        TContext
      > => {
      return useMutation(getDeleteListMutationOptions(options), queryClient);
    }
    export const getArchiveListUrl = (listId: string,) => {




  return `/lists/${listId}/archive`
}

/**
 * @summary Archive a list (Owner). Soft — items retained.
 */
export const archiveList = async (listId: string, options?: RequestInit): Promise<ListResponse> => {

  return customFetch<ListResponse>(getArchiveListUrl(listId),
  {
    ...options,
    method: 'POST'


  }
);}




export const getArchiveListMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof archiveList>>, TError,{listId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof archiveList>>, TError,{listId: string}, TContext> => {

const mutationKey = ['archiveList'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof archiveList>>, {listId: string}> = (props) => {
          const {listId} = props ?? {};

          return  archiveList(listId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ArchiveListMutationResult = NonNullable<Awaited<ReturnType<typeof archiveList>>>

    export type ArchiveListMutationError = ProblemDetails

    /**
 * @summary Archive a list (Owner). Soft — items retained.
 */
export const useArchiveList = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof archiveList>>, TError,{listId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof archiveList>>,
        TError,
        {listId: string},
        TContext
      > => {
      return useMutation(getArchiveListMutationOptions(options), queryClient);
    }
    export const getRestoreListUrl = (listId: string,) => {




  return `/lists/${listId}/restore`
}

/**
 * @summary Restore an archived list (Owner).
 */
export const restoreList = async (listId: string, options?: RequestInit): Promise<ListResponse> => {

  return customFetch<ListResponse>(getRestoreListUrl(listId),
  {
    ...options,
    method: 'POST'


  }
);}




export const getRestoreListMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof restoreList>>, TError,{listId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof restoreList>>, TError,{listId: string}, TContext> => {

const mutationKey = ['restoreList'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof restoreList>>, {listId: string}> = (props) => {
          const {listId} = props ?? {};

          return  restoreList(listId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RestoreListMutationResult = NonNullable<Awaited<ReturnType<typeof restoreList>>>

    export type RestoreListMutationError = ProblemDetails

    /**
 * @summary Restore an archived list (Owner).
 */
export const useRestoreList = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof restoreList>>, TError,{listId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof restoreList>>,
        TError,
        {listId: string},
        TContext
      > => {
      return useMutation(getRestoreListMutationOptions(options), queryClient);
    }
    export const getReorderListItemsUrl = (listId: string,) => {




  return `/lists/${listId}/order`
}

/**
 * Body `{ sortOrder }` — a fractional-index key generated between the neighbours the list was dropped between. Per-user: other members' ordering is untouched, and this does not count as a change to the list. Returned as `sortOrder` on the caller's `ListResponse`; lists the caller has never ordered come back null and sort by name after the ordered ones.
 * @summary Set the caller's own position for this list (Viewer+).
 */
export const reorderListItems = async (listId: string,
    setListOrderRequest: SetListOrderRequest, options?: RequestInit): Promise<ListResponse> => {

  return customFetch<ListResponse>(getReorderListItemsUrl(listId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(setListOrderRequest)
  }
);}




export const getReorderListItemsMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reorderListItems>>, TError,{listId: string;data: SetListOrderRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof reorderListItems>>, TError,{listId: string;data: SetListOrderRequest}, TContext> => {

const mutationKey = ['reorderListItems'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reorderListItems>>, {listId: string;data: SetListOrderRequest}> = (props) => {
          const {listId,data} = props ?? {};

          return  reorderListItems(listId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ReorderListItemsMutationResult = NonNullable<Awaited<ReturnType<typeof reorderListItems>>>
    export type ReorderListItemsMutationBody = SetListOrderRequest
    export type ReorderListItemsMutationError = ProblemDetails

    /**
 * @summary Set the caller's own position for this list (Viewer+).
 */
export const useReorderListItems = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reorderListItems>>, TError,{listId: string;data: SetListOrderRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reorderListItems>>,
        TError,
        {listId: string;data: SetListOrderRequest},
        TContext
      > => {
      return useMutation(getReorderListItemsMutationOptions(options), queryClient);
    }
    export const getAddListMemberUrl = (listId: string,) => {




  return `/lists/${listId}/members`
}

/**
 * Body `{ email, role? }`. Direct-add, no invite/accept. An unseen email provisions a placeholder principal (its `sub` is upgraded when the person first logs in). Members are returned with their `principalId`; use that for role change / removal.
 * @summary Add a member by email (any member; defaults to Editor).
 */
export const addListMember = async (listId: string,
    addMemberRequest: AddMemberRequest, options?: RequestInit): Promise<ListResponse> => {

  return customFetch<ListResponse>(getAddListMemberUrl(listId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(addMemberRequest)
  }
);}




export const getAddListMemberMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addListMember>>, TError,{listId: string;data: AddMemberRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof addListMember>>, TError,{listId: string;data: AddMemberRequest}, TContext> => {

const mutationKey = ['addListMember'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addListMember>>, {listId: string;data: AddMemberRequest}> = (props) => {
          const {listId,data} = props ?? {};

          return  addListMember(listId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddListMemberMutationResult = NonNullable<Awaited<ReturnType<typeof addListMember>>>
    export type AddListMemberMutationBody = AddMemberRequest
    export type AddListMemberMutationError = ProblemDetails

    /**
 * @summary Add a member by email (any member; defaults to Editor).
 */
export const useAddListMember = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addListMember>>, TError,{listId: string;data: AddMemberRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addListMember>>,
        TError,
        {listId: string;data: AddMemberRequest},
        TContext
      > => {
      return useMutation(getAddListMemberMutationOptions(options), queryClient);
    }
    export const getUpdateListMemberUrl = (listId: string,
    principalId: string,) => {




  return `/lists/${listId}/members/${principalId}`
}

/**
 * @summary Change a member's role by principal id (Owner only).
 */
export const updateListMember = async (listId: string,
    principalId: string,
    updateMemberRoleRequest: UpdateMemberRoleRequest, options?: RequestInit): Promise<ListResponse> => {

  return customFetch<ListResponse>(getUpdateListMemberUrl(listId,principalId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateMemberRoleRequest)
  }
);}




export const getUpdateListMemberMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateListMember>>, TError,{listId: string;principalId: string;data: UpdateMemberRoleRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateListMember>>, TError,{listId: string;principalId: string;data: UpdateMemberRoleRequest}, TContext> => {

const mutationKey = ['updateListMember'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateListMember>>, {listId: string;principalId: string;data: UpdateMemberRoleRequest}> = (props) => {
          const {listId,principalId,data} = props ?? {};

          return  updateListMember(listId,principalId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateListMemberMutationResult = NonNullable<Awaited<ReturnType<typeof updateListMember>>>
    export type UpdateListMemberMutationBody = UpdateMemberRoleRequest
    export type UpdateListMemberMutationError = ProblemDetails

    /**
 * @summary Change a member's role by principal id (Owner only).
 */
export const useUpdateListMember = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateListMember>>, TError,{listId: string;principalId: string;data: UpdateMemberRoleRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateListMember>>,
        TError,
        {listId: string;principalId: string;data: UpdateMemberRoleRequest},
        TContext
      > => {
      return useMutation(getUpdateListMemberMutationOptions(options), queryClient);
    }
    export const getRemoveListMemberUrl = (listId: string,
    principalId: string,) => {




  return `/lists/${listId}/members/${principalId}`
}

/**
 * @summary Remove a member by principal id, or leave (self). Last owner leaving deletes the list for everyone.
 */
export const removeListMember = async (listId: string,
    principalId: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getRemoveListMemberUrl(listId,principalId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getRemoveListMemberMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeListMember>>, TError,{listId: string;principalId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof removeListMember>>, TError,{listId: string;principalId: string}, TContext> => {

const mutationKey = ['removeListMember'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeListMember>>, {listId: string;principalId: string}> = (props) => {
          const {listId,principalId} = props ?? {};

          return  removeListMember(listId,principalId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RemoveListMemberMutationResult = NonNullable<Awaited<ReturnType<typeof removeListMember>>>

    export type RemoveListMemberMutationError = ProblemDetails

    /**
 * @summary Remove a member by principal id, or leave (self). Last owner leaving deletes the list for everyone.
 */
export const useRemoveListMember = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeListMember>>, TError,{listId: string;principalId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeListMember>>,
        TError,
        {listId: string;principalId: string},
        TContext
      > => {
      return useMutation(getRemoveListMemberMutationOptions(options), queryClient);
    }
