/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Lupira Tasks API
 * Task and command processing backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddMemberRequest,
  CreateListRequest,
  GetListsParams,
  ListCollectionResponse,
  ListResponse,
  ProblemDetails,
  SetListOrderRequest,
  UpdateListRequest,
  UpdateMemberRoleRequest
} from '../models';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetListsUrl = (params?: GetListsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/lists?${stringifiedParams}` : `/lists`
}

/**
 * `?archived=true` returns the caller's archived lists instead of the active ones.
 * @summary List the lists the caller is a member of.
 */
export const getLists = async (params?: GetListsParams, options?: RequestInit): Promise<ListCollectionResponse> => {

  return customFetch<ListCollectionResponse>(getGetListsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetListsQueryKey = (params?: GetListsParams,) => {
    return [
    `/lists`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetListsQueryOptions = <TData = Awaited<ReturnType<typeof getLists>>, TError = void>(params?: GetListsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLists>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetListsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLists>>> = ({ signal }) => getLists(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLists>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetListsQueryResult = NonNullable<Awaited<ReturnType<typeof getLists>>>
export type GetListsQueryError = void


export function useGetLists<TData = Awaited<ReturnType<typeof getLists>>, TError = void>(
 params: undefined |  GetListsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLists>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLists>>,
          TError,
          Awaited<ReturnType<typeof getLists>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLists<TData = Awaited<ReturnType<typeof getLists>>, TError = void>(
 params?: GetListsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLists>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLists>>,
          TError,
          Awaited<ReturnType<typeof getLists>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLists<TData = Awaited<ReturnType<typeof getLists>>, TError = void>(
 params?: GetListsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLists>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List the lists the caller is a member of.
 */

export function useGetLists<TData = Awaited<ReturnType<typeof getLists>>, TError = void>(
 params?: GetListsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLists>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetListsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPostListsUrl = () => {




  return `/lists`
}

/**
 * Body `{ id (GUIDv7), name, kind, color? }`. `kind` is `Todo`, `Shopping`, or `Agent` (agent/system-owned lists). Re-sending an existing id is an idempotent success.
 * @summary Create a list; the caller becomes Owner.
 */
export const postLists = async (createListRequest: CreateListRequest, options?: RequestInit): Promise<ListResponse> => {

  return customFetch<ListResponse>(getPostListsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createListRequest)
  }
);}




export const getPostListsMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLists>>, TError,{data: CreateListRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postLists>>, TError,{data: CreateListRequest}, TContext> => {

const mutationKey = ['postLists'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLists>>, {data: CreateListRequest}> = (props) => {
          const {data} = props ?? {};

          return  postLists(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostListsMutationResult = NonNullable<Awaited<ReturnType<typeof postLists>>>
    export type PostListsMutationBody = CreateListRequest
    export type PostListsMutationError = ProblemDetails | void

    /**
 * @summary Create a list; the caller becomes Owner.
 */
export const usePostLists = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLists>>, TError,{data: CreateListRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postLists>>,
        TError,
        {data: CreateListRequest},
        TContext
      > => {
      return useMutation(getPostListsMutationOptions(options), queryClient);
    }
    export const getGetListsListIdUrl = (listId: string,) => {




  return `/lists/${listId}`
}

/**
 * @summary Get a list with its members and tags (Viewer+).
 */
export const getListsListId = async (listId: string, options?: RequestInit): Promise<ListResponse> => {

  return customFetch<ListResponse>(getGetListsListIdUrl(listId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetListsListIdQueryKey = (listId: string,) => {
    return [
    `/lists/${listId}`
    ] as const;
    }


export const getGetListsListIdQueryOptions = <TData = Awaited<ReturnType<typeof getListsListId>>, TError = void>(listId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListId>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetListsListIdQueryKey(listId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getListsListId>>> = ({ signal }) => getListsListId(listId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: listId !== null && listId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getListsListId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetListsListIdQueryResult = NonNullable<Awaited<ReturnType<typeof getListsListId>>>
export type GetListsListIdQueryError = void


export function useGetListsListId<TData = Awaited<ReturnType<typeof getListsListId>>, TError = void>(
 listId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListsListId>>,
          TError,
          Awaited<ReturnType<typeof getListsListId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListsListId<TData = Awaited<ReturnType<typeof getListsListId>>, TError = void>(
 listId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListsListId>>,
          TError,
          Awaited<ReturnType<typeof getListsListId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListsListId<TData = Awaited<ReturnType<typeof getListsListId>>, TError = void>(
 listId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListId>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a list with its members and tags (Viewer+).
 */

export function useGetListsListId<TData = Awaited<ReturnType<typeof getListsListId>>, TError = void>(
 listId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListId>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetListsListIdQueryOptions(listId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPatchListsListIdUrl = (listId: string,) => {




  return `/lists/${listId}`
}

/**
 * Each provided field emits its own event. Set `colorProvided` to apply `color` (incl. clearing it). Send `simplePriority` (bool) to switch between simple on/off and the full 0..9 scale.
 * @summary Rename / recolor a list, or set its priority mode (Editor+).
 */
export const patchListsListId = async (listId: string,
    updateListRequest: UpdateListRequest, options?: RequestInit): Promise<ListResponse> => {

  return customFetch<ListResponse>(getPatchListsListIdUrl(listId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateListRequest)
  }
);}




export const getPatchListsListIdMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchListsListId>>, TError,{listId: string;data: UpdateListRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof patchListsListId>>, TError,{listId: string;data: UpdateListRequest}, TContext> => {

const mutationKey = ['patchListsListId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchListsListId>>, {listId: string;data: UpdateListRequest}> = (props) => {
          const {listId,data} = props ?? {};

          return  patchListsListId(listId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchListsListIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchListsListId>>>
    export type PatchListsListIdMutationBody = UpdateListRequest
    export type PatchListsListIdMutationError = ProblemDetails | void

    /**
 * @summary Rename / recolor a list, or set its priority mode (Editor+).
 */
export const usePatchListsListId = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchListsListId>>, TError,{listId: string;data: UpdateListRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchListsListId>>,
        TError,
        {listId: string;data: UpdateListRequest},
        TContext
      > => {
      return useMutation(getPatchListsListIdMutationOptions(options), queryClient);
    }
    export const getDeleteListsListIdUrl = (listId: string,) => {




  return `/lists/${listId}`
}

/**
 * @summary Delete a list (Owner). Tombstone — stream retained.
 */
export const deleteListsListId = async (listId: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getDeleteListsListIdUrl(listId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteListsListIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteListsListId>>, TError,{listId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteListsListId>>, TError,{listId: string}, TContext> => {

const mutationKey = ['deleteListsListId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteListsListId>>, {listId: string}> = (props) => {
          const {listId} = props ?? {};

          return  deleteListsListId(listId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteListsListIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteListsListId>>>

    export type DeleteListsListIdMutationError = void

    /**
 * @summary Delete a list (Owner). Tombstone — stream retained.
 */
export const useDeleteListsListId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteListsListId>>, TError,{listId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteListsListId>>,
        TError,
        {listId: string},
        TContext
      > => {
      return useMutation(getDeleteListsListIdMutationOptions(options), queryClient);
    }
    export const getPostListsListIdArchiveUrl = (listId: string,) => {




  return `/lists/${listId}/archive`
}

/**
 * @summary Archive a list (Owner). Soft — items retained.
 */
export const postListsListIdArchive = async (listId: string, options?: RequestInit): Promise<ListResponse> => {

  return customFetch<ListResponse>(getPostListsListIdArchiveUrl(listId),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostListsListIdArchiveMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postListsListIdArchive>>, TError,{listId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postListsListIdArchive>>, TError,{listId: string}, TContext> => {

const mutationKey = ['postListsListIdArchive'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postListsListIdArchive>>, {listId: string}> = (props) => {
          const {listId} = props ?? {};

          return  postListsListIdArchive(listId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostListsListIdArchiveMutationResult = NonNullable<Awaited<ReturnType<typeof postListsListIdArchive>>>

    export type PostListsListIdArchiveMutationError = void

    /**
 * @summary Archive a list (Owner). Soft — items retained.
 */
export const usePostListsListIdArchive = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postListsListIdArchive>>, TError,{listId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postListsListIdArchive>>,
        TError,
        {listId: string},
        TContext
      > => {
      return useMutation(getPostListsListIdArchiveMutationOptions(options), queryClient);
    }
    export const getPostListsListIdRestoreUrl = (listId: string,) => {




  return `/lists/${listId}/restore`
}

/**
 * @summary Restore an archived list (Owner).
 */
export const postListsListIdRestore = async (listId: string, options?: RequestInit): Promise<ListResponse> => {

  return customFetch<ListResponse>(getPostListsListIdRestoreUrl(listId),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostListsListIdRestoreMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postListsListIdRestore>>, TError,{listId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postListsListIdRestore>>, TError,{listId: string}, TContext> => {

const mutationKey = ['postListsListIdRestore'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postListsListIdRestore>>, {listId: string}> = (props) => {
          const {listId} = props ?? {};

          return  postListsListIdRestore(listId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostListsListIdRestoreMutationResult = NonNullable<Awaited<ReturnType<typeof postListsListIdRestore>>>

    export type PostListsListIdRestoreMutationError = void

    /**
 * @summary Restore an archived list (Owner).
 */
export const usePostListsListIdRestore = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postListsListIdRestore>>, TError,{listId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postListsListIdRestore>>,
        TError,
        {listId: string},
        TContext
      > => {
      return useMutation(getPostListsListIdRestoreMutationOptions(options), queryClient);
    }
    export const getPostListsListIdOrderUrl = (listId: string,) => {




  return `/lists/${listId}/order`
}

/**
 * Body `{ sortOrder }` — a fractional-index key generated between the neighbours the list was dropped between. Per-user: other members' ordering is untouched, and this does not count as a change to the list. Returned as `sortOrder` on the caller's `ListResponse`; lists the caller has never ordered come back null and sort by name after the ordered ones.
 * @summary Set the caller's own position for this list (Viewer+).
 */
export const postListsListIdOrder = async (listId: string,
    setListOrderRequest: SetListOrderRequest, options?: RequestInit): Promise<ListResponse> => {

  return customFetch<ListResponse>(getPostListsListIdOrderUrl(listId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(setListOrderRequest)
  }
);}




export const getPostListsListIdOrderMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postListsListIdOrder>>, TError,{listId: string;data: SetListOrderRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postListsListIdOrder>>, TError,{listId: string;data: SetListOrderRequest}, TContext> => {

const mutationKey = ['postListsListIdOrder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postListsListIdOrder>>, {listId: string;data: SetListOrderRequest}> = (props) => {
          const {listId,data} = props ?? {};

          return  postListsListIdOrder(listId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostListsListIdOrderMutationResult = NonNullable<Awaited<ReturnType<typeof postListsListIdOrder>>>
    export type PostListsListIdOrderMutationBody = SetListOrderRequest
    export type PostListsListIdOrderMutationError = ProblemDetails | void

    /**
 * @summary Set the caller's own position for this list (Viewer+).
 */
export const usePostListsListIdOrder = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postListsListIdOrder>>, TError,{listId: string;data: SetListOrderRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postListsListIdOrder>>,
        TError,
        {listId: string;data: SetListOrderRequest},
        TContext
      > => {
      return useMutation(getPostListsListIdOrderMutationOptions(options), queryClient);
    }
    export const getPostListsListIdMembersUrl = (listId: string,) => {




  return `/lists/${listId}/members`
}

/**
 * Body `{ email, role? }`. Direct-add, no invite/accept. An unseen email provisions a placeholder principal (its `sub` is upgraded when the person first logs in). Members are returned with their `principalId`; use that for role change / removal.
 * @summary Add a member by email (any member; defaults to Editor).
 */
export const postListsListIdMembers = async (listId: string,
    addMemberRequest: AddMemberRequest, options?: RequestInit): Promise<ListResponse> => {

  return customFetch<ListResponse>(getPostListsListIdMembersUrl(listId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(addMemberRequest)
  }
);}




export const getPostListsListIdMembersMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postListsListIdMembers>>, TError,{listId: string;data: AddMemberRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postListsListIdMembers>>, TError,{listId: string;data: AddMemberRequest}, TContext> => {

const mutationKey = ['postListsListIdMembers'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postListsListIdMembers>>, {listId: string;data: AddMemberRequest}> = (props) => {
          const {listId,data} = props ?? {};

          return  postListsListIdMembers(listId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostListsListIdMembersMutationResult = NonNullable<Awaited<ReturnType<typeof postListsListIdMembers>>>
    export type PostListsListIdMembersMutationBody = AddMemberRequest
    export type PostListsListIdMembersMutationError = ProblemDetails | void

    /**
 * @summary Add a member by email (any member; defaults to Editor).
 */
export const usePostListsListIdMembers = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postListsListIdMembers>>, TError,{listId: string;data: AddMemberRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postListsListIdMembers>>,
        TError,
        {listId: string;data: AddMemberRequest},
        TContext
      > => {
      return useMutation(getPostListsListIdMembersMutationOptions(options), queryClient);
    }
    export const getPatchListsListIdMembersPrincipalIdUrl = (listId: string,
    principalId: string,) => {




  return `/lists/${listId}/members/${principalId}`
}

/**
 * @summary Change a member's role by principal id (Owner only).
 */
export const patchListsListIdMembersPrincipalId = async (listId: string,
    principalId: string,
    updateMemberRoleRequest: UpdateMemberRoleRequest, options?: RequestInit): Promise<ListResponse> => {

  return customFetch<ListResponse>(getPatchListsListIdMembersPrincipalIdUrl(listId,principalId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateMemberRoleRequest)
  }
);}




export const getPatchListsListIdMembersPrincipalIdMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchListsListIdMembersPrincipalId>>, TError,{listId: string;principalId: string;data: UpdateMemberRoleRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof patchListsListIdMembersPrincipalId>>, TError,{listId: string;principalId: string;data: UpdateMemberRoleRequest}, TContext> => {

const mutationKey = ['patchListsListIdMembersPrincipalId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchListsListIdMembersPrincipalId>>, {listId: string;principalId: string;data: UpdateMemberRoleRequest}> = (props) => {
          const {listId,principalId,data} = props ?? {};

          return  patchListsListIdMembersPrincipalId(listId,principalId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchListsListIdMembersPrincipalIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchListsListIdMembersPrincipalId>>>
    export type PatchListsListIdMembersPrincipalIdMutationBody = UpdateMemberRoleRequest
    export type PatchListsListIdMembersPrincipalIdMutationError = ProblemDetails | void

    /**
 * @summary Change a member's role by principal id (Owner only).
 */
export const usePatchListsListIdMembersPrincipalId = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchListsListIdMembersPrincipalId>>, TError,{listId: string;principalId: string;data: UpdateMemberRoleRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchListsListIdMembersPrincipalId>>,
        TError,
        {listId: string;principalId: string;data: UpdateMemberRoleRequest},
        TContext
      > => {
      return useMutation(getPatchListsListIdMembersPrincipalIdMutationOptions(options), queryClient);
    }
    export const getDeleteListsListIdMembersPrincipalIdUrl = (listId: string,
    principalId: string,) => {




  return `/lists/${listId}/members/${principalId}`
}

/**
 * @summary Remove a member by principal id, or leave (self). Last owner leaving deletes the list for everyone.
 */
export const deleteListsListIdMembersPrincipalId = async (listId: string,
    principalId: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getDeleteListsListIdMembersPrincipalIdUrl(listId,principalId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteListsListIdMembersPrincipalIdMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteListsListIdMembersPrincipalId>>, TError,{listId: string;principalId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteListsListIdMembersPrincipalId>>, TError,{listId: string;principalId: string}, TContext> => {

const mutationKey = ['deleteListsListIdMembersPrincipalId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteListsListIdMembersPrincipalId>>, {listId: string;principalId: string}> = (props) => {
          const {listId,principalId} = props ?? {};

          return  deleteListsListIdMembersPrincipalId(listId,principalId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteListsListIdMembersPrincipalIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteListsListIdMembersPrincipalId>>>

    export type DeleteListsListIdMembersPrincipalIdMutationError = ProblemDetails | void

    /**
 * @summary Remove a member by principal id, or leave (self). Last owner leaving deletes the list for everyone.
 */
export const useDeleteListsListIdMembersPrincipalId = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteListsListIdMembersPrincipalId>>, TError,{listId: string;principalId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteListsListIdMembersPrincipalId>>,
        TError,
        {listId: string;principalId: string},
        TContext
      > => {
      return useMutation(getDeleteListsListIdMembersPrincipalIdMutationOptions(options), queryClient);
    }
