/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Lupira Tasks API
 * Task and command processing backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateRelationRequest,
  DeleteListsListIdItemsItemIdRelationsParams,
  ProblemDetails,
  RelationDto
} from '../models';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getPostListsListIdItemsItemIdRelationsUrl = (listId: string,
    itemId: string,) => {




  return `/lists/${listId}/items/${itemId}/relations`
}

/**
 * Body `{ toKind, toRef, relationType, metadata? }`. `toKind` e.g. `cal-item` (the checking heartbeat Prompt) or `url` (issue/PR/incident/release). `relationType` e.g. `monitors`, `spawned-by`, `produced`, `blocked-by`, `relates-to`. Idempotent: re-linking the same edge is a no-op.
 * @summary Link a task to a cal-api Prompt heartbeat or an external ref (Editor+).
 */
export const postListsListIdItemsItemIdRelations = async (listId: string,
    itemId: string,
    createRelationRequest: CreateRelationRequest, options?: RequestInit): Promise<RelationDto> => {

  return customFetch<RelationDto>(getPostListsListIdItemsItemIdRelationsUrl(listId,itemId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createRelationRequest)
  }
);}




export const getPostListsListIdItemsItemIdRelationsMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postListsListIdItemsItemIdRelations>>, TError,{listId: string;itemId: string;data: CreateRelationRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postListsListIdItemsItemIdRelations>>, TError,{listId: string;itemId: string;data: CreateRelationRequest}, TContext> => {

const mutationKey = ['postListsListIdItemsItemIdRelations'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postListsListIdItemsItemIdRelations>>, {listId: string;itemId: string;data: CreateRelationRequest}> = (props) => {
          const {listId,itemId,data} = props ?? {};

          return  postListsListIdItemsItemIdRelations(listId,itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostListsListIdItemsItemIdRelationsMutationResult = NonNullable<Awaited<ReturnType<typeof postListsListIdItemsItemIdRelations>>>
    export type PostListsListIdItemsItemIdRelationsMutationBody = CreateRelationRequest
    export type PostListsListIdItemsItemIdRelationsMutationError = ProblemDetails | void

    /**
 * @summary Link a task to a cal-api Prompt heartbeat or an external ref (Editor+).
 */
export const usePostListsListIdItemsItemIdRelations = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postListsListIdItemsItemIdRelations>>, TError,{listId: string;itemId: string;data: CreateRelationRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postListsListIdItemsItemIdRelations>>,
        TError,
        {listId: string;itemId: string;data: CreateRelationRequest},
        TContext
      > => {
      return useMutation(getPostListsListIdItemsItemIdRelationsMutationOptions(options), queryClient);
    }
    export const getGetListsListIdItemsItemIdRelationsUrl = (listId: string,
    itemId: string,) => {




  return `/lists/${listId}/items/${itemId}/relations`
}

/**
 * @summary List a task's relations (Viewer+).
 */
export const getListsListIdItemsItemIdRelations = async (listId: string,
    itemId: string, options?: RequestInit): Promise<RelationDto[]> => {

  return customFetch<RelationDto[]>(getGetListsListIdItemsItemIdRelationsUrl(listId,itemId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetListsListIdItemsItemIdRelationsQueryKey = (listId: string,
    itemId: string,) => {
    return [
    `/lists/${listId}/items/${itemId}/relations`
    ] as const;
    }


export const getGetListsListIdItemsItemIdRelationsQueryOptions = <TData = Awaited<ReturnType<typeof getListsListIdItemsItemIdRelations>>, TError = void>(listId: string,
    itemId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListIdItemsItemIdRelations>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetListsListIdItemsItemIdRelationsQueryKey(listId,itemId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getListsListIdItemsItemIdRelations>>> = ({ signal }) => getListsListIdItemsItemIdRelations(listId,itemId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: listId !== null && listId !== undefined && itemId !== null && itemId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getListsListIdItemsItemIdRelations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetListsListIdItemsItemIdRelationsQueryResult = NonNullable<Awaited<ReturnType<typeof getListsListIdItemsItemIdRelations>>>
export type GetListsListIdItemsItemIdRelationsQueryError = void


export function useGetListsListIdItemsItemIdRelations<TData = Awaited<ReturnType<typeof getListsListIdItemsItemIdRelations>>, TError = void>(
 listId: string,
    itemId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListIdItemsItemIdRelations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListsListIdItemsItemIdRelations>>,
          TError,
          Awaited<ReturnType<typeof getListsListIdItemsItemIdRelations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListsListIdItemsItemIdRelations<TData = Awaited<ReturnType<typeof getListsListIdItemsItemIdRelations>>, TError = void>(
 listId: string,
    itemId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListIdItemsItemIdRelations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListsListIdItemsItemIdRelations>>,
          TError,
          Awaited<ReturnType<typeof getListsListIdItemsItemIdRelations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListsListIdItemsItemIdRelations<TData = Awaited<ReturnType<typeof getListsListIdItemsItemIdRelations>>, TError = void>(
 listId: string,
    itemId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListIdItemsItemIdRelations>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List a task's relations (Viewer+).
 */

export function useGetListsListIdItemsItemIdRelations<TData = Awaited<ReturnType<typeof getListsListIdItemsItemIdRelations>>, TError = void>(
 listId: string,
    itemId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListsListIdItemsItemIdRelations>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetListsListIdItemsItemIdRelationsQueryOptions(listId,itemId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getDeleteListsListIdItemsItemIdRelationsUrl = (listId: string,
    itemId: string,
    params: DeleteListsListIdItemsItemIdRelationsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/lists/${listId}/items/${itemId}/relations?${stringifiedParams}` : `/lists/${listId}/items/${itemId}/relations`
}

/**
 * Identify the edge with `?toKind=&toRef=&relationType=`. Idempotent: removing a link that isn't there is a no-op (204).
 * @summary Remove a task relation by its edge tuple (Editor+).
 */
export const deleteListsListIdItemsItemIdRelations = async (listId: string,
    itemId: string,
    params: DeleteListsListIdItemsItemIdRelationsParams, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getDeleteListsListIdItemsItemIdRelationsUrl(listId,itemId,params),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteListsListIdItemsItemIdRelationsMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteListsListIdItemsItemIdRelations>>, TError,{listId: string;itemId: string;params: DeleteListsListIdItemsItemIdRelationsParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteListsListIdItemsItemIdRelations>>, TError,{listId: string;itemId: string;params: DeleteListsListIdItemsItemIdRelationsParams}, TContext> => {

const mutationKey = ['deleteListsListIdItemsItemIdRelations'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteListsListIdItemsItemIdRelations>>, {listId: string;itemId: string;params: DeleteListsListIdItemsItemIdRelationsParams}> = (props) => {
          const {listId,itemId,params} = props ?? {};

          return  deleteListsListIdItemsItemIdRelations(listId,itemId,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteListsListIdItemsItemIdRelationsMutationResult = NonNullable<Awaited<ReturnType<typeof deleteListsListIdItemsItemIdRelations>>>

    export type DeleteListsListIdItemsItemIdRelationsMutationError = ProblemDetails | void

    /**
 * @summary Remove a task relation by its edge tuple (Editor+).
 */
export const useDeleteListsListIdItemsItemIdRelations = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteListsListIdItemsItemIdRelations>>, TError,{listId: string;itemId: string;params: DeleteListsListIdItemsItemIdRelationsParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteListsListIdItemsItemIdRelations>>,
        TError,
        {listId: string;itemId: string;params: DeleteListsListIdItemsItemIdRelationsParams},
        TContext
      > => {
      return useMutation(getDeleteListsListIdItemsItemIdRelationsMutationOptions(options), queryClient);
    }
