/**
 * Generated by orval 🍺
 * Do not edit manually.
 * LupiraTasks BFF
 * Task and command processing backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddMemberRequest,
  CreateListRequest,
  ListDto,
  ListListsParams,
  ProblemDetails,
  SetListOrderRequest,
  UpdateListRequest,
  UpdateMemberRoleRequest
} from '../models';

import { customFetch } from '../../fetcher';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getListListsUrl = (params?: ListListsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/lists?${stringifiedParams}` : `/lists`
}

/**
 * `?archived=true` returns the caller's archived lists instead of the active ones.
 * @summary List the lists the caller is a member of.
 */
export const listLists = async (params?: ListListsParams, options?: Parameters<typeof customFetch>[1]): Promise<ListDto[]> => {

  return customFetch<ListDto[]>(getListListsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListListsQueryKey = (params?: ListListsParams,) => {
    return [
    `/lists`, ...(params ? [params] : [])
    ] as const;
    }


export const getListListsQueryOptions = <TData = Awaited<ReturnType<typeof listLists>>, TError = ProblemDetails>(params?: ListListsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLists>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListListsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listLists>>> = ({ signal }) => listLists(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listLists>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListListsQueryResult = NonNullable<Awaited<ReturnType<typeof listLists>>>
export type ListListsQueryError = ProblemDetails


export function useListLists<TData = Awaited<ReturnType<typeof listLists>>, TError = ProblemDetails>(
 params: undefined |  ListListsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLists>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listLists>>,
          TError,
          Awaited<ReturnType<typeof listLists>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListLists<TData = Awaited<ReturnType<typeof listLists>>, TError = ProblemDetails>(
 params?: ListListsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLists>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listLists>>,
          TError,
          Awaited<ReturnType<typeof listLists>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListLists<TData = Awaited<ReturnType<typeof listLists>>, TError = ProblemDetails>(
 params?: ListListsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLists>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List the lists the caller is a member of.
 */

export function useListLists<TData = Awaited<ReturnType<typeof listLists>>, TError = ProblemDetails>(
 params?: ListListsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLists>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListListsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getCreateListUrl = () => {




  return `/lists`
}

/**
 * Body `{ id (GUIDv7), name, kind, color? }`. `kind` is `Todo`, `Shopping`, or `Agent` (agent/system-owned lists). Re-sending an existing id is an idempotent success.
 * @summary Create a list; the caller becomes Owner.
 */
export const createList = async (createListRequest: CreateListRequest, options?: Parameters<typeof customFetch>[1]): Promise<ListDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<ListDto>(getCreateListUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createListRequest)
  }
);}





export const getCreateListMutationKey = () => ['createList'] as const;

export const getCreateListMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createList>>, TError,CreateListMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createList>>, TError,CreateListMutationVariables, TContext> => {

const mutationKey = getCreateListMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createList>>, CreateListMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createList(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateListMutationResult = NonNullable<Awaited<ReturnType<typeof createList>>>
    export type CreateListMutationBody = CreateListRequest
    export type CreateListMutationError = ProblemDetails
    export type CreateListMutationVariables = {data: CreateListRequest}

    /**
 * @summary Create a list; the caller becomes Owner.
 */
export const useCreateList = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createList>>, TError,CreateListMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createList>>,
        TError,
        CreateListMutationVariables,
        TContext
      > => {
      return useMutation(getCreateListMutationOptions(options), queryClient);
    }
    export const getGetListUrl = (listId: string,) => {




  return `/lists/${listId}`
}

/**
 * @summary Get a list with its members and tags (Viewer+).
 */
export const getList = async (listId: string, options?: Parameters<typeof customFetch>[1]): Promise<ListDto> => {

  return customFetch<ListDto>(getGetListUrl(listId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetListQueryKey = (listId: string,) => {
    return [
    `/lists/${listId}`
    ] as const;
    }


export const getGetListQueryOptions = <TData = Awaited<ReturnType<typeof getList>>, TError = ProblemDetails>(listId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetListQueryKey(listId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getList>>> = ({ signal }) => getList(listId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: listId !== null && listId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetListQueryResult = NonNullable<Awaited<ReturnType<typeof getList>>>
export type GetListQueryError = ProblemDetails


export function useGetList<TData = Awaited<ReturnType<typeof getList>>, TError = ProblemDetails>(
 listId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getList>>,
          TError,
          Awaited<ReturnType<typeof getList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetList<TData = Awaited<ReturnType<typeof getList>>, TError = ProblemDetails>(
 listId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getList>>,
          TError,
          Awaited<ReturnType<typeof getList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetList<TData = Awaited<ReturnType<typeof getList>>, TError = ProblemDetails>(
 listId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a list with its members and tags (Viewer+).
 */

export function useGetList<TData = Awaited<ReturnType<typeof getList>>, TError = ProblemDetails>(
 listId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetListQueryOptions(listId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getUpdateListUrl = (listId: string,) => {




  return `/lists/${listId}`
}

/**
 * Each provided field emits its own event. Set `colorProvided` to apply `color` (incl. clearing it). Send `simplePriority` (bool) to switch between simple on/off and the full 0..9 scale.
 * @summary Rename / recolor a list, or set its priority mode (Editor+).
 */
export const updateList = async (listId: string,
    updateListRequest: UpdateListRequest, options?: Parameters<typeof customFetch>[1]): Promise<ListDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<ListDto>(getUpdateListUrl(listId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateListRequest)
  }
);}





export const getUpdateListMutationKey = () => ['updateList'] as const;

export const getUpdateListMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateList>>, TError,UpdateListMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateList>>, TError,UpdateListMutationVariables, TContext> => {

const mutationKey = getUpdateListMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateList>>, UpdateListMutationVariables> = (props) => {
          const {listId,data} = props ?? {};

          return  updateList(listId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateListMutationResult = NonNullable<Awaited<ReturnType<typeof updateList>>>
    export type UpdateListMutationBody = UpdateListRequest
    export type UpdateListMutationError = ProblemDetails
    export type UpdateListMutationVariables = {listId: string;data: UpdateListRequest}

    /**
 * @summary Rename / recolor a list, or set its priority mode (Editor+).
 */
export const useUpdateList = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateList>>, TError,UpdateListMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateList>>,
        TError,
        UpdateListMutationVariables,
        TContext
      > => {
      return useMutation(getUpdateListMutationOptions(options), queryClient);
    }
    export const getDeleteListUrl = (listId: string,) => {




  return `/lists/${listId}`
}

/**
 * @summary Delete a list (Owner). Tombstone — stream retained.
 */
export const deleteList = async (listId: string, options?: Parameters<typeof customFetch>[1]): Promise<void> => {

  return customFetch<void>(getDeleteListUrl(listId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteListMutationKey = () => ['deleteList'] as const;

export const getDeleteListMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteList>>, TError,DeleteListMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteList>>, TError,DeleteListMutationVariables, TContext> => {

const mutationKey = getDeleteListMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteList>>, DeleteListMutationVariables> = (props) => {
          const {listId} = props ?? {};

          return  deleteList(listId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteListMutationResult = NonNullable<Awaited<ReturnType<typeof deleteList>>>

    export type DeleteListMutationError = ProblemDetails
    export type DeleteListMutationVariables = {listId: string}

    /**
 * @summary Delete a list (Owner). Tombstone — stream retained.
 */
export const useDeleteList = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteList>>, TError,DeleteListMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteList>>,
        TError,
        DeleteListMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteListMutationOptions(options), queryClient);
    }
    export const getArchiveListUrl = (listId: string,) => {




  return `/lists/${listId}/archive`
}

/**
 * @summary Archive a list (Owner). Soft — items retained.
 */
export const archiveList = async (listId: string, options?: Parameters<typeof customFetch>[1]): Promise<ListDto> => {

  return customFetch<ListDto>(getArchiveListUrl(listId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getArchiveListMutationKey = () => ['archiveList'] as const;

export const getArchiveListMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof archiveList>>, TError,ArchiveListMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof archiveList>>, TError,ArchiveListMutationVariables, TContext> => {

const mutationKey = getArchiveListMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof archiveList>>, ArchiveListMutationVariables> = (props) => {
          const {listId} = props ?? {};

          return  archiveList(listId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ArchiveListMutationResult = NonNullable<Awaited<ReturnType<typeof archiveList>>>

    export type ArchiveListMutationError = ProblemDetails
    export type ArchiveListMutationVariables = {listId: string}

    /**
 * @summary Archive a list (Owner). Soft — items retained.
 */
export const useArchiveList = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof archiveList>>, TError,ArchiveListMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof archiveList>>,
        TError,
        ArchiveListMutationVariables,
        TContext
      > => {
      return useMutation(getArchiveListMutationOptions(options), queryClient);
    }
    export const getAddListMemberUrl = (listId: string,) => {




  return `/lists/${listId}/members`
}

/**
 * Body `{ email, role? }`. Direct-add, no invite/accept. An unseen email provisions a placeholder principal (its `sub` is upgraded when the person first logs in). Members are returned with their `principalId`; use that for role change / removal.
 * @summary Add a member by email (any member; defaults to Editor).
 */
export const addListMember = async (listId: string,
    addMemberRequest: AddMemberRequest, options?: Parameters<typeof customFetch>[1]): Promise<ListDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<ListDto>(getAddListMemberUrl(listId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(addMemberRequest)
  }
);}





export const getAddListMemberMutationKey = () => ['addListMember'] as const;

export const getAddListMemberMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addListMember>>, TError,AddListMemberMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof addListMember>>, TError,AddListMemberMutationVariables, TContext> => {

const mutationKey = getAddListMemberMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addListMember>>, AddListMemberMutationVariables> = (props) => {
          const {listId,data} = props ?? {};

          return  addListMember(listId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddListMemberMutationResult = NonNullable<Awaited<ReturnType<typeof addListMember>>>
    export type AddListMemberMutationBody = AddMemberRequest
    export type AddListMemberMutationError = ProblemDetails
    export type AddListMemberMutationVariables = {listId: string;data: AddMemberRequest}

    /**
 * @summary Add a member by email (any member; defaults to Editor).
 */
export const useAddListMember = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addListMember>>, TError,AddListMemberMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addListMember>>,
        TError,
        AddListMemberMutationVariables,
        TContext
      > => {
      return useMutation(getAddListMemberMutationOptions(options), queryClient);
    }
    export const getUpdateListMemberUrl = (listId: string,
    principalId: string,) => {




  return `/lists/${listId}/members/${principalId}`
}

/**
 * @summary Change a member's role by principal id (Owner only).
 */
export const updateListMember = async (listId: string,
    principalId: string,
    updateMemberRoleRequest: UpdateMemberRoleRequest, options?: Parameters<typeof customFetch>[1]): Promise<ListDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<ListDto>(getUpdateListMemberUrl(listId,principalId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateMemberRoleRequest)
  }
);}





export const getUpdateListMemberMutationKey = () => ['updateListMember'] as const;

export const getUpdateListMemberMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateListMember>>, TError,UpdateListMemberMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateListMember>>, TError,UpdateListMemberMutationVariables, TContext> => {

const mutationKey = getUpdateListMemberMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateListMember>>, UpdateListMemberMutationVariables> = (props) => {
          const {listId,principalId,data} = props ?? {};

          return  updateListMember(listId,principalId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateListMemberMutationResult = NonNullable<Awaited<ReturnType<typeof updateListMember>>>
    export type UpdateListMemberMutationBody = UpdateMemberRoleRequest
    export type UpdateListMemberMutationError = ProblemDetails
    export type UpdateListMemberMutationVariables = {listId: string;principalId: string;data: UpdateMemberRoleRequest}

    /**
 * @summary Change a member's role by principal id (Owner only).
 */
export const useUpdateListMember = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateListMember>>, TError,UpdateListMemberMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateListMember>>,
        TError,
        UpdateListMemberMutationVariables,
        TContext
      > => {
      return useMutation(getUpdateListMemberMutationOptions(options), queryClient);
    }
    export const getRemoveListMemberUrl = (listId: string,
    principalId: string,) => {




  return `/lists/${listId}/members/${principalId}`
}

/**
 * @summary Remove a member by principal id, or leave (self). Last owner leaving deletes the list for everyone.
 */
export const removeListMember = async (listId: string,
    principalId: string, options?: Parameters<typeof customFetch>[1]): Promise<void> => {

  return customFetch<void>(getRemoveListMemberUrl(listId,principalId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getRemoveListMemberMutationKey = () => ['removeListMember'] as const;

export const getRemoveListMemberMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeListMember>>, TError,RemoveListMemberMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof removeListMember>>, TError,RemoveListMemberMutationVariables, TContext> => {

const mutationKey = getRemoveListMemberMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeListMember>>, RemoveListMemberMutationVariables> = (props) => {
          const {listId,principalId} = props ?? {};

          return  removeListMember(listId,principalId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RemoveListMemberMutationResult = NonNullable<Awaited<ReturnType<typeof removeListMember>>>

    export type RemoveListMemberMutationError = ProblemDetails
    export type RemoveListMemberMutationVariables = {listId: string;principalId: string}

    /**
 * @summary Remove a member by principal id, or leave (self). Last owner leaving deletes the list for everyone.
 */
export const useRemoveListMember = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeListMember>>, TError,RemoveListMemberMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeListMember>>,
        TError,
        RemoveListMemberMutationVariables,
        TContext
      > => {
      return useMutation(getRemoveListMemberMutationOptions(options), queryClient);
    }
    export const getReorderListItemsUrl = (listId: string,) => {




  return `/lists/${listId}/order`
}

/**
 * Body `{ sortOrder }` — a fractional-index key generated between the neighbours the list was dropped between. Per-user: other members' ordering is untouched, and this does not count as a change to the list. Returned as `sortOrder` on the caller's `ListDto`; lists the caller has never ordered come back null and sort by name after the ordered ones.
 * @summary Set the caller's own position for this list (Viewer+).
 */
export const reorderListItems = async (listId: string,
    setListOrderRequest: SetListOrderRequest, options?: Parameters<typeof customFetch>[1]): Promise<ListDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<ListDto>(getReorderListItemsUrl(listId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(setListOrderRequest)
  }
);}





export const getReorderListItemsMutationKey = () => ['reorderListItems'] as const;

export const getReorderListItemsMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reorderListItems>>, TError,ReorderListItemsMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof reorderListItems>>, TError,ReorderListItemsMutationVariables, TContext> => {

const mutationKey = getReorderListItemsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reorderListItems>>, ReorderListItemsMutationVariables> = (props) => {
          const {listId,data} = props ?? {};

          return  reorderListItems(listId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ReorderListItemsMutationResult = NonNullable<Awaited<ReturnType<typeof reorderListItems>>>
    export type ReorderListItemsMutationBody = SetListOrderRequest
    export type ReorderListItemsMutationError = ProblemDetails
    export type ReorderListItemsMutationVariables = {listId: string;data: SetListOrderRequest}

    /**
 * @summary Set the caller's own position for this list (Viewer+).
 */
export const useReorderListItems = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reorderListItems>>, TError,ReorderListItemsMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reorderListItems>>,
        TError,
        ReorderListItemsMutationVariables,
        TContext
      > => {
      return useMutation(getReorderListItemsMutationOptions(options), queryClient);
    }
    export const getRestoreListUrl = (listId: string,) => {




  return `/lists/${listId}/restore`
}

/**
 * @summary Restore an archived list (Owner).
 */
export const restoreList = async (listId: string, options?: Parameters<typeof customFetch>[1]): Promise<ListDto> => {

  return customFetch<ListDto>(getRestoreListUrl(listId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getRestoreListMutationKey = () => ['restoreList'] as const;

export const getRestoreListMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof restoreList>>, TError,RestoreListMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof restoreList>>, TError,RestoreListMutationVariables, TContext> => {

const mutationKey = getRestoreListMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof restoreList>>, RestoreListMutationVariables> = (props) => {
          const {listId} = props ?? {};

          return  restoreList(listId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RestoreListMutationResult = NonNullable<Awaited<ReturnType<typeof restoreList>>>

    export type RestoreListMutationError = ProblemDetails
    export type RestoreListMutationVariables = {listId: string}

    /**
 * @summary Restore an archived list (Owner).
 */
export const useRestoreList = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof restoreList>>, TError,RestoreListMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof restoreList>>,
        TError,
        RestoreListMutationVariables,
        TContext
      > => {
      return useMutation(getRestoreListMutationOptions(options), queryClient);
    }
