// The estate's icon vocabulary: one name per concept, so swapping family is a one-file edit.
// Byte-identical across the three SPAs; the mobile apps map the same concepts to MaterialIcons
// in their own `ui/icons.ts`. Import from here, never from `@mui/icons-material` directly.

export { default as AccountIcon } from '@mui/icons-material/AccountCircleOutlined';
export { default as AddIcon } from '@mui/icons-material/AddOutlined';
export { default as AlertIcon } from '@mui/icons-material/ErrorOutlineOutlined';
export { default as BatteryIcon } from '@mui/icons-material/BatteryStdOutlined';
export { default as BoltIcon } from '@mui/icons-material/BoltOutlined';
export { default as BuildIcon } from '@mui/icons-material/BuildOutlined';
export { default as BusinessIcon } from '@mui/icons-material/BusinessOutlined';
export { default as CakeIcon } from '@mui/icons-material/CakeOutlined';
export { default as CalendarIcon } from '@mui/icons-material/CalendarMonthOutlined';
export { default as CelebrationIcon } from '@mui/icons-material/CelebrationOutlined';
export { default as CheckIcon } from '@mui/icons-material/CheckOutlined';
export { default as CheckCircleIcon } from '@mui/icons-material/CheckCircleOutlined';
export { default as CheckboxBlankIcon } from '@mui/icons-material/CheckBoxOutlineBlankOutlined';
export { default as CheckboxIcon } from '@mui/icons-material/CheckBoxOutlined';
export { default as ChecklistIcon } from '@mui/icons-material/ChecklistOutlined';
export { default as ChevronLeftIcon } from '@mui/icons-material/ChevronLeftOutlined';
export { default as ChevronRightIcon } from '@mui/icons-material/ChevronRightOutlined';
export { default as ClearIcon } from '@mui/icons-material/ClearOutlined';
export { default as CloseIcon } from '@mui/icons-material/CloseOutlined';
export { default as CloudIcon } from '@mui/icons-material/CloudOutlined';
export { default as CollapseIcon } from '@mui/icons-material/CloseFullscreenOutlined';
export { default as ContactsIcon } from '@mui/icons-material/ContactsOutlined';
export { default as DeleteIcon } from '@mui/icons-material/DeleteOutlined';
export { default as DragIcon } from '@mui/icons-material/DragIndicatorOutlined';
// Distinct from ExpandIcon on purpose: this is a select's affordance, that is a disclosure.
export { default as DropdownIcon } from '@mui/icons-material/ArrowDropDownOutlined';
export { default as EmailIcon } from '@mui/icons-material/EmailOutlined';
export { default as EventAvailableIcon } from '@mui/icons-material/EventAvailableOutlined';
export { default as ExpandFullIcon } from '@mui/icons-material/OpenInFullOutlined';
export { default as ExpandIcon } from '@mui/icons-material/ExpandMoreOutlined';
export { default as FilterIcon } from '@mui/icons-material/FilterListOutlined';
export { default as FolderIcon } from '@mui/icons-material/FolderOpenOutlined';
export { default as GroupIcon } from '@mui/icons-material/GroupOutlined';
export { default as InboxIcon } from '@mui/icons-material/InboxOutlined';
export { default as LayersIcon } from '@mui/icons-material/LayersOutlined';
export { default as LinkIcon } from '@mui/icons-material/LinkOutlined';
export { default as ListIcon } from '@mui/icons-material/ViewListOutlined';
export { default as LocationOffIcon } from '@mui/icons-material/LocationOffOutlined';
export { default as LockIcon } from '@mui/icons-material/LockOutlined';
export { default as MapIcon } from '@mui/icons-material/MapOutlined';
export { default as MenuIcon } from '@mui/icons-material/MenuOutlined';
export { default as MoreIcon } from '@mui/icons-material/MoreHorizOutlined';
export { default as MovieIcon } from '@mui/icons-material/MovieOutlined';
export { default as OpenInNewIcon } from '@mui/icons-material/OpenInNewOutlined';
export { default as PeopleIcon } from '@mui/icons-material/PeopleOutlined';
export { default as PersonIcon } from '@mui/icons-material/PersonOutlined';
export { default as PhotosIcon } from '@mui/icons-material/PhotoLibraryOutlined';
export { default as PlaceIcon } from '@mui/icons-material/PlaceOutlined';
export { default as PowerIcon } from '@mui/icons-material/PowerSettingsNewOutlined';
export { default as RestoreIcon } from '@mui/icons-material/RestoreOutlined';
export { default as SearchIcon } from '@mui/icons-material/SearchOutlined';
export { default as SettingsIcon } from '@mui/icons-material/SettingsOutlined';
export { default as StarIcon } from '@mui/icons-material/StarOutlined';
export { default as StarOutlineIcon } from '@mui/icons-material/StarBorderOutlined';
export { default as TuneIcon } from '@mui/icons-material/TuneOutlined';
