name: ci

on:
  pull_request:
  push:
    branches-ignore: [main]

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    with:
      run_integration: ${{ contains(github.event.pull_request.labels.*.name, 'integration') }}
